### ISSUE TITLE
add Latex support

### ISSUE THREAD

**Issue by revolunet** [revolunet/sublimetext-markdown-preview#17]
see https://github.com/morlay/sublimetext-markdown-preview fork

**Comment by facelessuser** [comment]
It sounds like the general workaround is sufficient for people to get mathematical expression with LaTex.  It also appears that no more work is planned on this.

Obviously this can only really be controlled in Python Markdown, but if the current workaround is not sufficient we can revisit this with a Python Markdown plugin (that is how I personally approach it), but in general, I haven't heard of any complaints in regards to the current offering.  I think this can generally be closed.
