### ISSUE TITLE
Sublime freezes for a few seconds when saving

### ISSUE THREAD

**Issue by garyking** [revolunet/sublimetext-markdown-preview#233]
I noticed that ST3 will freeze for a few seconds when this package is enabled. Is it performing some sort of action when I save? 

Is this expected? How can I fix this? Thanks in advance!

**Comment by vohof** [comment]
I think you need to enable some sort of threading to prevent sublime text from "freezing":

> To prevent a poor connection from interrupting other work, we need to make sure that the Prefixr API calls are happening in the background. If you don't know anything about threading, a very basic explanation is that threads are a way for a program to schedule multiple sets of code to run seemingly at the same time. It is essential in our case because it lets the code that is sending data to, and waiting for a response from, the Prefixr API from preventing the rest of the Sublime user interface from freezing.

http://code.tutsplus.com/tutorials/how-to-create-a-sublime-text-2-plugin--net-22685
