### ISSUE TITLE
Build multiple files at once

### ISSUE THREAD

**Issue by naychrist** [revolunet/sublimetext-markdown-preview#243]
Hi there, thanks for the great plugin. I'd love to be able to use it to build multiple files by either selecting multiple files or a folder in the sidebar before using the command palette. I use markdown wikis for documenting projects, which usually takes a few pages. Would be great to be able to quickly generate html documentation for clients from this.

**Comment by facelessuser** [comment]
It doesn't look like anyone working on the project has interest in reworking  Markdown Preview to handle batch processing.  Pull requests are welcome and the best way to get features in.  If this is still a desire, I would instead approach this issue again with a pull request.
