### ISSUE TITLE
Double hyphen \ dash parsed as single character with built-in parser

### ISSUE THREAD

**Issue by DavidLemayian** [revolunet/sublimetext-markdown-preview#244]
This happens even in code block when I type `--` it is displayed as &#8211; .

Similar problem: http://stackoverflow.com/questions/16871088/how-to-escape-double-dash-in-markdown

**Comment by facelessuser** [comment]
Issue #262 will fix this issue.  Most of the work is now done, and I should be making the pull sometime soon.

**Comment by DavidLemayian** [comment]
@facelessuser That is brilliant! Thank you.

**Comment by facelessuser** [comment]
Resolved in [1.2.0](https://github.com/revolunet/sublimetext-markdown-preview/releases/tag/1.2.0)

**Comment by DavidLemayian** [comment]
:+1:
