### ISSUE TITLE
How do you override the CSS for Markdown Preview?

### ISSUE THREAD

**Issue by specialorange** [revolunet/sublimetext-markdown-preview#254]
Do you do it in the MarkdownPreview.sublime-settings ?   In the source file?

Running Mac OSX 10.10 and Sublime Build 3065.  Thanks for your help!

Not sure how to put the `question` label on this in Github....

**Comment by tvogt** [comment]
I also can't get the override to work, and neither myfile.css nor myfile.md.css yields the expected result.

**Comment by specialorange** [comment]
@tvogt  Did you try my image example above?   Can you provide more details?

**Comment by tvogt** [comment]
I tried. Now after reading another webpage on this topic, I think I misunderstood what "overrides" means. It gets appended, it does not replace the default css. With that information and checking everything again, I just got this working right now.

FYI: The correct extension is .css and not .md.css

**Comment by rsalgado** [comment]
@tvogt Like you and @tonholis, I also misunderstood the instructions in the settings comment and tried using a `.md.css` file. Maybe a **rewording of the comment in the settings file** would help people to avoid making the same mistake, like me, after all this time.

**Comment by cglacet** [comment]
Yep ! Same. If `<md_file_name>.css` exists, then `<md_file_name>.markdown_filetype` will use this file as a CSS instead of the default one.

**Comment by facelessuser** [comment]
This will get documented in the next release.  It's close to being done.  I just keep getting distracted.
