### ISSUE TITLE
How to use MathJax

### ISSUE THREAD

**Issue by MikeHoffert** [revolunet/sublimetext-markdown-preview#260]
How do you get a formula to load with MathJax? I've added `"enable_mathjax": true,` to my user config, yet the example given in the readme is not converted to a math formula (the leading and trailing slashes are removed, but that's it).

Is there something more that has to be done or some other setting to set?

**Comment by MikeHoffert** [comment]
My bad, it needs two slashes, which the Github readme doesn't show, but source shows.

**Comment by revolunet** [comment]
Would be very nice if you could fix the readme ;)
