### ISSUE TITLE
Just "simple" translation into "copy to clipboard"?

### ISSUE THREAD

**Issue by snnwolf** [revolunet/sublimetext-markdown-preview#263]
Hi!
I like your plugin. It's great :+1: 

I would like to have a "simple HTML" saving option when "copy to clipboard": just my Markdown in HTML file, no template nor doctypes or CSS styles. Just translating my Markdown into HTML equivalent.
But I would like preview html with template and css.
Is it possible?

**Comment by TimothyBramlett** [comment]
Would love this also!

**Comment by qgates** [comment]
You can get close to what you want by changing MarkdownPreview's user prefs thus:
```
{
	"css": "none",
}
```
This will strip the CSS leaving only doctype, html and aricle.markdown-body tags remaining. Then use the clipboard or export HTML in Sublime options of MDP. It should be fairly straightforward to add an option to remove these tags as well, but that would require a little modification to the plugin.

**Comment by snnwolf** [comment]
Thanks for tip!!!
