### ISSUE TITLE
It can't highlight the markdown file

### ISSUE THREAD

**Issue by bigpotato920** [revolunet/sublimetext-markdown-preview#266]
I install markdown-preview in sublime3, it can preview the markdown file in the browser correctly, but it can't highlight the markdown file in subl3, even if I turn "enable_highlight" to true in markdown preview user configuration file.

**Comment by facelessuser** [comment]
Do you mean syntax highlighting of fenced blocks?

**Comment by facelessuser** [comment]
Okay, you are going to have to participate in the conversation to get help.  I will have to close the issue if I don't get any response.

Please post your configuration file etc. So I can see what you are doing.   Manually configuring Codehilite can override the `enable_highlight` feature if I recall correctly.

**Comment by garfieldnate** [comment]
I just installed and I *thought* I had this issue, but I just needed to restart. Usually I don't have to restart ST when installing a plugin, but this time I did (though I'm on ST 2).

**Comment by facelessuser** [comment]
@garfieldnate yeah some plugins need restarts sometimes after updating.  This is usually because the main file gets reloaded and the supporting libraries don't get properly reloaded.

**Comment by facelessuser** [comment]
I am closing this issue because I have not heard any response from the issue creator in two weeks.
