### ISSUE TITLE
Can't find "Markdown Preview" in Command Palette

### ISSUE THREAD

**Issue by VirgilMing** [revolunet/sublimetext-markdown-preview#267]
Freshly installed the plugin but no option shown.
OS X 10.10.2, Sublime Text 2.0.2

**Comment by facelessuser** [comment]
How did you install? The recommended way is via Package Control.  Do you see errors in your console that can help us understand what is going on?

**Comment by facelessuser** [comment]
I will have to close this issue if there is no participation.  Please continue the conversation so we can resolve your issue.  If there is no response in 5 more days, I will close the issue.

**Comment by VirgilMing** [comment]
I must have missed this notification... Sorry
I did install it through Package Control.

Here is the console output when fresh start:
startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/virgilming/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/virgilming/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 9 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/0_package_control_loader/02-bz2.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./02-bz2.py", line 2, in <module>
    from package_control import sys_path
ImportError: No module named package_control
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/ConvertToUTF8/ConvertToUTF8.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Fold Comments/foldcomments.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/GBK Encoding Support/sublime_gbk.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/delete_temp_files.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/getTeXRoot.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/jumpToPDF.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/latexCommand.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/latexEnvCloser.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/latexEnvironment.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/latex_cite_completions.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/latex_ref_cite_completions.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/latex_ref_completions.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/makePDF.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/migrate.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/parseTeXlog.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/texMacro.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/texSections.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/toggle_auto.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/toggle_focus.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/toggle_fwdsync.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/toggle_show.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/viewPDF.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Package Control/bootstrap.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage_commands.py
Reloading plugin /Users/virgilming/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage_motions.py
plugin init time: 0.369914
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.891417
using gamma: 2 (err: 6.9282)
startup cache, total files: 114 cache hits: 114
startup time: 1.07705 (package setup was not run)
loaded 848 snippets
Package Control: No updated packages
no command for selector: noop:
no command for selector: noop:
no command for selector: insertSingleQuoteIgnoringSubstitution:

**Comment by facelessuser** [comment]
I don't see your log showing Markdown Preview even being loaded.  Are you sure that Package Control doesn't have Markdown Preview in the disabled list?

**Comment by VirgilMing** [comment]
Well, I have to say no...

—

**Comment by facelessuser** [comment]
You should check by accessing the `Package Control: Enable Package` or something like that.  If Markdown Preview is in the list, that is why, and you should enable it.  Package Control sometimes disables my packages.  I assume this occurs on upgrades: disable package, upgrade package, re-enable, but sometimes the re-enable doesn't occur.

**Comment by VirgilMing** [comment]
Problem solved. Thank you.

—
