### ISSUE TITLE
no highlighting in preview

### ISSUE THREAD

**Issue by owenrumney** [revolunet/sublimetext-markdown-preview#268]
I feel like I must be doing something basic wrong

I'm adding a block to a markdown file using fencing

```python
def square (x):
    return x * x
```

When I preview the code its not highlighted, looking at the source its all classed up, but no css files are being loaded. Am I missing something silly?

**Comment by facelessuser** [comment]
Please post your settings so I can better help.

**Comment by facelessuser** [comment]
Also post platform and sublime version.

**Comment by facelessuser** [comment]
This has been open 8 days with no response.  I will close this issue after 14 days.

**Comment by owenrumney** [comment]
apologies for delay, reinstalled and worked second time.
