### ISSUE TITLE
Issues setting default browser

### ISSUE THREAD

**Issue by pbrianmackey** [revolunet/sublimetext-markdown-preview#269]
My default browser is Chrome.  Markdown preview goes to firefox.  I went to markdown user settings in Sublime Text > Preferences > Package Settings > Markdown Preview > Settings - User and added:

```javascript
{
    "browser": "/Applications/Google Chrome.app"
}
```

And still I get FireFox.  

Environment:  OSX Yosemite 10.10.2

**Comment by facelessuser** [comment]
I know this has been open for a long time.  I will try and reproduce, but if I cannot reproduce, I will need more info, or I will have to close this.  I will let you know what I find.

**Comment by facelessuser** [comment]
I am afraid I cannot reproduce this on OSX.  If you are able to reopen with more info, I'd be happy to look at it again, but as of right now, I will have to close this.
