### ISSUE TITLE
Is Markdown.tmlanguage included in this package?

### ISSUE THREAD

**Issue by PaleNeutron** [revolunet/sublimetext-markdown-preview#274]
I could not find `Markdown.tmlanguage` in the zip file or set syntax to `Markdown` in ST3 after this package installed.

I have to install `Markdown Extend` to enable build system or the build system is bind to `plain text`.

PS: is there any syntax highlighting package recommanded?   
`Markdown Extend` highlight nearly nothing...   
`Markdown Edit` goes too far and `Markdown Light` only performs light theme.

**Comment by facelessuser** [comment]
Nope, this is a plugin for previewing markdown in HTML.  There is no general support for syntax highlighting contained in this package.

Highlighting is provided by the default Markdown plugin included with sublime or by some other 3rd part plugin you download from package control.
