### ISSUE TITLE
can not load strapdown.js

### ISSUE THREAD

**Issue by weijarz** [revolunet/sublimetext-markdown-preview#277]
The script referenced by preview html 
`/home/wjzhou/.config/sublime-text-3/Installed%20Packages/Strapdown%20Markdown%20Preview.sublime-package/strapdown/strapdown.js` is unaccessible from browser because this file is located in a .sublime-package file (not a dir).

**Comment by facelessuser** [comment]
You have the wrong repository.  This plugin doesn't use strapdown.
