### ISSUE TITLE
    "html_template": "/home/test/customized-template-sample.html" not work

### ISSUE THREAD

**Issue by skipify** [revolunet/sublimetext-markdown-preview#278]
"html_template": "/home/test/customized-template-sample.html" not work

**Comment by facelessuser** [comment]
There could be many reasons why this doesn't work for you, but I cannot begin to guess since you have provided so little information.

**Comment by facelessuser** [comment]
Without more info, I am going to have to close this issue.  Please provide Sublime version, any errors you see in the console, your template.  A description of what `not work` means.  If I don't receive some kind of response by the weekend, I will close this issue.

**Comment by skipify** [comment]
Sorry, I changed a computer,it's ok. may be with some different python package in my system out some problems.
