### ISSUE TITLE
Tasks Lists don't render correctly in GitHub Browser preview

### ISSUE THREAD

**Issue by CheungJ** [revolunet/sublimetext-markdown-preview#280]
When previewing in the browser using GitHub markdown, the tasks lists don't render correctly. They show as the literal characters that were typed into the mardown file: - [] task 1

Steps to reproduce:
1. In Sublime Text 3, create a new file
2. Set the syntax to markdown
3. Try to create a task list like this: - [] task 1
4. Select the text
5. Press CTRL+SHIFT+P
6. Choose: Markdown Preview: Preview in Browser->github

You will see that the tasks list isn't correct:
![incorrect tasks list](https://cloud.githubusercontent.com/assets/2295409/7425407/2590800a-efa8-11e4-8d3c-0380665ddd4f.png)

To see what it should render as, see the 'extras' tab in this documentation:
https://guides.github.com/features/mastering-markdown/

**Comment by facelessuser** [comment]
See issue #256.

**Comment by CheungJ** [comment]
That worked. Thanks for the link and apologies for not seeing it myself.

**Comment by CheungJ** [comment]
Duplicate of issue #256
