### ISSUE TITLE
Update 3rd party doc links

### ISSUE THREAD

**Issue by facelessuser** [revolunet/sublimetext-markdown-preview#281]
Recently some of the third party doc links have been broken because  I switched to using mkdocs to generate docs.  The site's structure in general is a bit different, and now the doc link references in this plugin are now broken.

On a side note, during this time it may be useful to update to the latest versions of the 3rd party plugins to ensure the latest docs match what is shown here.

**Comment by revolunet** [comment]
mmm which doc ?

**Comment by facelessuser** [comment]
If you are referring to the doc links, it is to the third party Markdown extension doc links on the readme.  I just need to update the links.  The extension docs are [here](http://facelessuser.github.io/PyMdown/user-guide/pymdown-extensions/).

If you are referring to the doc generator, I am using [mkdocs](http://www.mkdocs.org/).  Nice package wrapped around Python Markdown.  So you can use all the Python Markdown extensions (built-in or third party).  It has an easy way to deploy your doc site to gh-pages. It has a live preview of the site as you edit it.  It's still in development, but even extremely useful in in its current state.  The new release coming even integrates search and a number of useful improvements (I am currently using their dev branch until the next release drops to take advantage of the search integration).  It's still in development, but very useful.  When they hit a 1.0 release, I think it is going to be very useful for project documentation.  Github readme and wikis are frankly limited, this really opens up the possibility for easy doc site deployment with markdown.
