### ISSUE TITLE
Syntax highlighting colors differ from this and GitHub's Markdown

### ISSUE THREAD

**Issue by saadq** [revolunet/sublimetext-markdown-preview#283]
You can see the difference in the syntax highlighting colors between this:

![](http://i.imgur.com/toZZx6z.png)

and GitHub's Markdown:

![](http://i.imgur.com/ae5a1HN.png)

**Comment by facelessuser** [comment]
1. Are you using the "Github" parser or the "Markdown" parser option?

2. If you are using the "Markdown" option, it is not the Github parser, but it is Python Markdown (with Pygments) so 100% Github look and feel is not possible, and if you change options you can deviate further from it.  Further, Github used to use Pygments just like Python Markdown, but now they use a custom highlighter that Python Markdown is no longer able to 100% mimic.

3. If using the Github parser, a CSS file is provided ripped straight from Github via https://github.com/sindresorhus/github-markdown-css, but Github can't leave things alone, so they are constantly mucking with their style.  In the last year, I have seen their syntax highlighter change multiple times, so don't expect Markdown Preview to always have the very latest.

4. If not having the latest CSS for the Github parser is distressing, you can pick up the latest CSS from above and issue a pull request.  Either that, or wait till someone else is finally ready to update it.

Hope that helps!

**Comment by saadq** [comment]
This was the GitHub parser and it isn't a big deal, I just assumed that your colors were inaccurately chosen. Thanks for the clarification!
