### ISSUE TITLE
adding additional CL args to MMD binary

### ISSUE THREAD

**Issue by jamessince79** [revolunet/sublimetext-markdown-preview#285]
Might there be a way to add the ability to include additional command line arguments specific to the multimarkdown binary that would be passed during build? Specifically, I'm aiming to pass the `--random` argument at build, but can find now way to do this currently. 

thanks

**Comment by facelessuser** [comment]
This is related to #284. It is likely that a generic command to call external markdown tools will be created allowing users to control what tool it points to, and what arguments get feed in.  That would give you the ability to set whatever you want.

**Comment by facelessuser** [comment]
I am going to close this issue as it is a duplicate, and #284 will track the progress.
