### ISSUE TITLE
Convert md to html

### ISSUE THREAD

**Issue by egiova** [revolunet/sublimetext-markdown-preview#286]
When prompt Ctrl+Shift+p, what am I supposed to enter as information in console area appearing as parsers can operate? Documentation is very confusing (sorry about that, maybe I am stupid and I don't know yet).

**Comment by egiova** [comment]
Sorry, I finally understood what was my issue. My brain is slow, and my eyes don't read everything. There's maybe a connection by the way. Thanks. And sorry again.

**Comment by revolunet** [comment]
you're not stupid, the documentation can be confusing and you're invited to improve it if you can :)

Ctrl+Shift+p opens the sublime text palette where you can execute builtin commands, and plugins too

From there, just type "markdown" and select "markdown preview: preview in browser"

**Comment by egiova** [comment]
(See my comment above) Thanks for your answer.

**Comment by egiova** [comment]
By the way... You put as NOTE crucial information actually. That's what confused me actually. I mean it's essential to understand that output, or conversion, has to be throught GitHub. So the process is easier to understand later on.

**Comment by revolunet** [comment]
it doesnt have to be, you have the choice between github parser or builtin markdown parser
