### ISSUE TITLE
How/where do you set the parser config to github?

### ISSUE THREAD

**Issue by briankung** [revolunet/sublimetext-markdown-preview#287]
The readme instructions are vague. Any additional help would be appreciated.

**Comment by unitof** [comment]
Hi there!

Easy access to the config file is tucked up in Sublime Text's context menus:
**OS X:** `Sublime Text > Preferences > Package Settings > Markdown Preview > Settings – User`
**Windows:** `Preferences > Package Settings > Markdown Preview > Settings – User`

This works like a JSON file. Anything you set here will override the default settings. You need to add the line `"parser": "github"` to this file, but you need to add it using JSON syntax. JSON is that language that is in an unhealthy relationship with curly braces and colons. If this is the only config option you are setting, your entire `MarkdownPreview.sublime-settings` file should be

```javascript
{
  "parser": "github"
}
```

But! If you are setting any other options, you've gotta delineate them with commas, for example:

```javascript
{
  "parser": "github", // note the comma
  "build_action": "sublime"
}
```

Maybe you already know how JSON works and all that, but I just recently figured it out.

And all the documentation you're looking for is probably sitting in `Preferences > Package Settings > Markdown Preview > Settings – Default`. It's a read-only file but you can use it to figure out what you want your User Settings to override. It's where I learned how to do this!

**Comment by briankung** [comment]
Thanks for looking into this, @unitof. The `parser` option doesn't have any effect on the command palette, which is the main way that I use the markdown preview, but I did look into the settings and find a way to disable the other parsers, so thank you for the tip.

**Comment by briankung** [comment]
FWIW, I set `"enabled_parsers"`to `["github"]`

**Comment by unitof** [comment]
Ah, gotcha. Sounds good!

**Comment by facelessuser** [comment]
Sounds like this issue has been solved, so I will close it.
