### ISSUE TITLE
'default' browser option no longer working

### ISSUE THREAD

**Issue by Gabriel-p** [revolunet/sublimetext-markdown-preview#288]
Today I attempted to use the preview and the package kept opening a file called `xx.html` (where `xx` was some number) within Sublime.

I had to manually set in the user settings file:

````
{
    "browser": "google-chrome",
}
````

for it to work again.

**Comment by itsalaidbacklife** [comment]
I've had the same problem. It's worth noting that the value "google-chrome" needs to be a valid path to your browser, right? Meaning this won't work if chrome isn't added to your path. It didn't work for me until I changed the JSON value to "chrome" from "google-chrome."

**Comment by facelessuser** [comment]
@itsalaidbacklife, it sounds like you stumbled on the answer.  Further, the documentation in the setting file even explains that you may need to enter a **full** path:

```js
    /*
        Sets the default opener for HTML files
        default - Use the system default HTML viewer
        other - Set a full path to any executable. ex: /Applications/Google Chrome Canary.app or /Applications/Firefox.app
    */
```

I think this is very clear.

**Comment by facelessuser** [comment]
As this sounds more like a user error, I will close the issue.  Feel free to open it if you are still having issues, or can provide more info.

**Comment by matthiasg** [comment]
i have just had the same issue. the browser did not open , instead it showed the generated html in a sublime tab. when setting the browser setting explicitly to the full chrome path instead of default it worked correctly.
