### ISSUE TITLE
Image relative URL

### ISSUE THREAD

**Issue by matej-zajacik** [revolunet/sublimetext-markdown-preview#291]
In my markdown document, I have the following line:

    ![AI sight cone](pics/ai_sight_01.png "AI sight cone")

So I would expect it to generate this HTML:

    <img src="pics/ai_sight_01.png" title="AI sight cone" alt="AI sight cone"/>

But instead, it generates this:

    <img src="///d://my_docs/my_game/game_docs/pics/ai_sight_01.png" title="AI sight cone" alt="AI sight cone"/>

My folder / file structure is this:

* game_docs
    * pics
        * ai_sight_01.png
    * game_doc.md
    * game_doc.html (generated from md)

Is there a way to retain relative URLs in images, links, etc. when generating HTML output?

**Comment by kjdelisle** [comment]
I can confirm that I'm also having this issue, both with the GFM syntax for generating links and image links, as well as when attempting to manually fill in the HTML with relative path links (they get converted to incorrect absolute paths instead).

Example:
```html
<a href="path/to/thingy.txt">Thingy!</a>
<img alt="I am a picture!" src="path/to/pics/happyFunTime.jpg" />
```
becomes
```html
<a href="///C://Users/bobthebuilder/path/to/thingy.txt">Thingy!</a>
<img alt="I am a picture!" src="///C://Users/bobthebuilder/path/to/pics/happyFunTime.jpg" />
```

**Comment by unitof** [comment]
Seems to be Windows-specific. On OS X Yosemite with Sublime Text 3 (Build 3083)

```markdown
![AI sight cone](pics/ai_sight_01.png "AI sight cone")
```

builds as

```html
<img src="pics/ai_sight_01.png" alt="AI sight cone" title="AI sight cone" style="max-width:100%;">
```

which is the expected behavior.

**Comment by matej-zajacik** [comment]
Guys, there is no bug. The plugin has many settings in which you can set conversion rules for links and images.

Go to `Preferences -> Package Settings -> Markdown Preview -> Settings - User` and add this:

	{
		"image_path_conversion": "relative",
		"file_path_conversion": "relative",
	}

My bad for not realizing this.

**Comment by revolunet** [comment]
Thanks for reporting :)

**Comment by kjdelisle** [comment]
Works perfectly now, thanks!

**Comment by unitof** [comment]
Coolio! How come those settings were the default for my install, but not yours?

**Comment by matej-zajacik** [comment]
I'm wondering the same thing, unitof.
