### ISSUE TITLE
When parser set to github, heading elements lack proper #id attributes

### ISSUE THREAD

**Issue by unitof** [revolunet/sublimetext-markdown-preview#293]
It seems that when `"parser": "github"` is specified in one's user settings, all heading tags (`<h1>` through `<h6`) in the built HTML lack `id` attributes. The little anchor chainlink icons still show up on hover and properly update the address bar with what the section link *should* be, but that link does not scroll to any particular section because no element on the page actually has the corresponding `#id`.

**Comment by facelessuser** [comment]
Did you enable the following?

```js
    /*
        Enables a post process to inject header ids to ensure hrefs to headers work
    */
    "github_inject_header_ids": false,
```

Github's API for some reason doesn't inject the header ids except when in `gfm` mode, but only injects the anchors in `markdown` mode.  It's weird.  Anyways, I threw in the crude header id injection that can be enabled with the switch above.   It probably breaks down on headers with additional tags embedded in them, but it should work fine for the average everyday text headers.  One of these days, I should update it to be more robust (or maybe someone else will get to it first).

**Comment by unitof** [comment]
`"github_inject_header_ids": true` works wonderfully and you're amazing.

I just found #208 while tracing where that config option came from. Sorry I missed it before and thank you so much for building this. You're a gentleman and a coder.

**Comment by math2001** [comment]
Why is the default value to `false`?

**Comment by facelessuser** [comment]
@math2001, Mainly due to the way it works as described in my post earlier.  Depending on what github mode you have on, it won't work, and its robustness is questionable.  It was a quick and dirty workaround I threw together.  If people want to use it, they can turn it on, but some might not care.
