### ISSUE TITLE
Can no longer install markdown preview

### ISSUE THREAD

**Issue by emettely** [revolunet/sublimetext-markdown-preview#295]
```
ImportError: No module named markdown_preview_lib.pygments.lexers._asy_builtins
Reloading plugin /Users/user/Library/Application Support/Sublime Text 2/Packages/Markdown Preview/MarkdownPreview.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./MarkdownPreview.py", line 49, in <module>
    from markdown_wrapper import StMarkdown as Markdown
  File "./markdown_wrapper.py", line 25, in <module>
    __import__("lib.markdown_preview_lib.pygments.%s.%s" % (parent, mod[:-3]))
ImportError: No module named markdown_preview_lib.pygments.lexers._asy_builtins
```
I am not sure why this is happening, please help!

**Comment by emettely** [comment]
Also I have tried to install the plugin manually - unfortunately, sublime 2 stopped opening after, so I had to delete it.

**Comment by emettely** [comment]
Another thing is that I have looked into the markdown preview plugin file and the lexers asy builtins do exist...

**Comment by facelessuser** [comment]
Pygments is no longer included with Markdown Preview, but it instead uses the Package Control dependency Pygments.  This actually imports Pygments cleanly and without modifications to Pygments which is better.  It should work fine for you now.

Now keep in mind if some other plugin tries to include Pygments with their package and tries to load it to the system path, you may have two versions of Pygments clashing.  What they should do is use the Pygments dependency or access Pygments relatively.

Anyways, hopefully this is now resolved.
