### ISSUE TITLE
Support for Markdown tables in preview

### ISSUE THREAD

**Issue by supermartzin** [revolunet/sublimetext-markdown-preview#297]
Hi,

I noticed that this plugin doesn't support tables with pipes syntax in previews.

**Example** table:

| Column 1 | Column 2 | Column 3 |
| :------: | :-------:| :----: |
| row 1 | item | another item |

Syntax:

```
| Column 1 | Column 2 | Column 3 |
| :------: | :------: | :------: |
|  row 1   |   item   | another item |
```

Are you planning to add it?

Thanks.

**Comment by facelessuser** [comment]
If using the Python Markdown parser, you will have to remove the  spaces between the pipes and the colons, but if you are using the github parser, then it should handle them just like Github does.

If you think the Python Markdown parser should handle this, then you should create an issue over at Python Markdown.

**Comment by supermartzin** [comment]
Okay, I found what was causing the problem.

I had my table inside unordered list and from above and below without newline. After adding newline it works great!

Thanks for help.
