### ISSUE TITLE
[security] [bug] HTML preview using Python-markdown  is vulnerable to XSS

### ISSUE THREAD

**Issue by AndreyMZ** [revolunet/sublimetext-markdown-preview#299]
HTML preview using Python-markdown is vulnerable (at lest with default settings) to Cross-site scripting attack (XSS).
Must use HTML sanitizer (at least by default).

References:
- https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-%28and-how-to-mitigate-it%29
- https://michelf.ca/blog/2010/markdown-and-xss/
- https://pythonhosted.org/Markdown/reference.html#safe_mode

**Comment by facelessuser** [comment]
> https://pythonhosted.org/Markdown/reference.html#safe_mode

Safe mode is not safe and should not be relied upon to protect against attacks; it is not a sanitizer and enabling it and telling people it protects them would be disingenuous .  This is why it has been deprecated and will be removed in the future for Python Markdown.  Not only that, it would only work for Python Markdown and not work for other Markdown parsers that are used with Markdown Preview.  I imagine the Github parser already sanitizes HTML on Githubs end though, so Github might already be okay.

> Must use HTML sanitizer (at least by default).

I think this is a good idea, but I would call this a feature request and not a bug.  Nowhere is it claimed to be a hardened Markdown Preview.  You should be careful if you are loading strange Markdown into your webbrowser.  I use it on my own projects and on files that I have looked over and deemed safe.  As of right now, the current policy is don't load up strange markdown you are unfamiliar with without looking it over.

With that said, if you really desire this, your best chance of getting it in is to put together a pull request as this plugin is mainly supported via pull requests,

1. You would need to find a pretty good sanitizer (safe mode is not going to work and would be more harmful to make people think it offers some kind real protection).

2. It should be performed as the last thing on the file, so probably added as a post process event in the Markdown Preview code.  Alternatively, you could probably write a Python Markdown extension that gets run as the final event, but this would only work for Python Markdown.

3. It should be optional, and probably also have its strictness configurable.

I help out on this repository sometimes when I have time and tackle various issues, but that is occurring less and less for me in recent days.  While I plan on tackling a few small issues via pull request soon, I probably won't be touching this one, so do consider a pull request.

**Comment by facelessuser** [comment]
As this isn't really a bug I am going to close this.  As mentioned before, pull requests are welcome, and that is the best way to get such a feature in here.
