### ISSUE TITLE
Strikethrough support

### ISSUE THREAD

**Issue by VipSaran** [revolunet/sublimetext-markdown-preview#301]
~~Stroke~~ Strike through is supported by [GitHub markdown](https://help.github.com/articles/github-flavored-markdown/) as well as some big names (like [Trello](https://trello.com/c/lzWiUQYd/53-add-strikethrough)).

Could `sublimetext-markdown-preview` support it too?

**Comment by facelessuser** [comment]
You need to check [features](https://github.com/revolunet/sublimetext-markdown-preview#features-).  If you use the `delete` extension, you can do strike through.

**Comment by VipSaran** [comment]
Thanks.
I did search for it, but never thought it could be named "crossed out".

**Comment by facelessuser** [comment]
Yeah, strike through would make more sense.  I will give past me a good talking to so it doesn't happen again :wink:.  I've got a pull coming up sometime soon, I will try and update that along with everything else I plan on addressing.

**Comment by VipSaran** [comment]
:+1:
