### ISSUE TITLE
Feature suggestion: CSS overrides

### ISSUE THREAD

**Issue by jkgeyti** [revolunet/sublimetext-markdown-preview#305]
**Suggestion:** Enable a user's ability to add/correct css, instead of having to replace entire stylesheet.

**Reasoning:** I wish to stay updated with updates and improvements to the mainline css file, and I want to be able to have the extension automatically switch between `markdown.css` and `github.css`. At the same time, I want to make minor corrections, that are most likely to keep working (stuff like page width and body background color, for instance).

**Possible solution 1:** Change `css` in config from a string value to a list of string values, such that we can add an additional css file (e.g. `"css": ["default", "/path/to/my/corrections.css"]`

**Possible solution 2:** Add an inline css field to the config, such as `"user_css": "body { background-color: red ; }"`

**Comment by facelessuser** [comment]
Solution 1: seems like a reasonable request.  I wouldn't mind doing this.  If I get some time soon, I will look into this.

**Comment by zibuyule** [comment]
When it released version 1.3.3? I very much hope it.

**Comment by facelessuser** [comment]
I just haven't gotten around to merging it yet.   It is on my list when I sent down to work on plugins again.
