### ISSUE TITLE
Unable to find target command: markdown_build

### ISSUE THREAD

**Issue by Albinutte** [revolunet/sublimetext-markdown-preview#306]
Everything seemed to work great just yesterday, but now I can't even build html with the following error: 
`Unable to find target command: markdown_build`

I tried to reinstall the package / sublime, but it didn't do the trick. What could have possibly gone wrong? Any help would be appreciated.

**Comment by facelessuser** [comment]
Please look at console and report errors here if any.  I will take a look tonight.  It was a fairly big update internally.

**Comment by facelessuser** [comment]
Please also provide as much detail as you can, system, ST version etc.

**Comment by facelessuser** [comment]
On ST3 it is working for me.  A restart was required after the update.

**Comment by facelessuser** [comment]
Most likely related to #306

**Comment by facelessuser** [comment]
I meant #307

**Comment by facelessuser** [comment]
Closed duplicate of #307.
