### ISSUE TITLE
Stopped working on SublimeText 2 Windows

### ISSUE THREAD

**Issue by DannyBen** [revolunet/sublimetext-markdown-preview#307]
I no longer have the "Preview Markdown" option in the menu.

Uninstall and reinstall did not help.

It worked several days ago.

**Comment by facelessuser** [comment]
Are you seeing errors in the console?

**Comment by facelessuser** [comment]
Please also provide as much detail as you can, system etc.

**Comment by facelessuser** [comment]
Also, did you restart after the update?   A big update like the one pushed out will likely not reload well via Package Control and will require a Sublime restart.

**Comment by facelessuser** [comment]
I did test this before the release, and I just verified again that it is working for me in both OSX and Windows ST2, so you will need to provide more details. For further investigation.

**Comment by DannyBen** [comment]
Ok. More details.

#### 0. System

- Windows 10
- Sublime Text 2

#### 1. Package Control Remove - console output
```
Package Control: The package Markdown Preview has been removed and will be cleaned up on the next restart
reloading /C/Users/Danny/AppData/Roaming/Sublime Text 2/Packages/User/Package Control.sublime-settings
Package Control: The orphaned dependency pygments has been removed
Unloading plugin C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\01-pygments.py
Package Control: The orphaned dependency pyyaml has been removed
Unloading plugin C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\50-pyyaml.py
```

#### 2. Restarted sublime

#### 3. Package Control Install - console output

```
Reloading plugin C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\helper.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\abbr.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\admonition.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\attr_list.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\codehilite.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\def_list.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\delete.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\extra.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\fenced_code.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\footnotes.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\github.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\githubemoji.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\headeranchor.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\helper.py", line 67, in <module>
    __import__(package)
  File ".\markdown\extensions\headeranchor.py", line 35, in <module>
    from .toc import slugify, stashedHTML2text, unique, TocExtension
  File ".\markdown\extensions\toc.py", line 23, in <module>
    import unicodedata
ImportError: No module named unicodedata
Reloading plugin C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown_settings.py
Reloading plugin C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown_wrapper.py
Reloading plugin C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\MarkdownPreview.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\abbr.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\admonition.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\attr_list.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\codehilite.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\def_list.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\delete.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\extra.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\fenced_code.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\footnotes.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\github.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\githubemoji.py
Reloading plugin extension C:\Users\Danny\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\headeranchor.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\MarkdownPreview.py", line 49, in <module>
    from helper import INSTALLED_DIRECTORY
  File ".\helper.py", line 67, in <module>
    __import__(package)
  File ".\markdown\extensions\headeranchor.py", line 35, in <module>
    from .toc import slugify, stashedHTML2text, unique, TocExtension
  File ".\markdown\extensions\toc.py", line 23, in <module>
    import unicodedata
ImportError: No module named unicodedata
found 8 files for base name Main.sublime-menu
theme loaded
reloading /C/Users/Danny/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Soda Light Modded.sublime-theme
theme loaded
```


Let me know what else you need.

**Comment by facelessuser** [comment]
I think that is all I need.   It can't find unicodedata.  I need to revisit why some systems can't find this on ST2.   I think some of Markdown Previews internal dependencies had some hacks for this,  but when we removed the internal dependencies for package control managed dependencies, we lost the advantage of those ST2 specific hacks.  I need to put those back in. 

I will add the fix later, but I will need you to test them locally for verification as I am not experiencing this problem.

**Comment by DannyBen** [comment]
Sure thing.

**Comment by cjhgo** [comment]
i suffer the same problem.hope the fix.

**Comment by facelessuser** [comment]
Found the hack: https://github.com/revolunet/sublimetext-markdown-preview/commit/b631e1d57221a6a3fec582258e5cfd15d1f855cd.

Will probably need to put this at the top level in `MarkdownPreview.py`.  I will get to this after work today.

**Comment by Albinutte** [comment]
Looks like my problem, thanks for looking into it

**Comment by facelessuser** [comment]
If someone with unicodedata can try out #308 pull request and let me know if it solves your problems, I will be able to push out a new bug fix release.

**Comment by hkant** [comment]
my sublime2 in windows 8 also can not show markdown preview .and the console show "Reloading plugin extension C:\Users\zhuwj\AppData\Roaming\Sublime Text 2\Packages\Markdown Preview\markdown\extensions\headeranchor.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\helper.py", line 67, in <module>
    __import__(package)
  File ".\markdown\extensions\headeranchor.py", line 35, in <module>
    from .toc import slugify, stashedHTML2text, unique, TocExtension
  File ".\markdown\extensions\toc.py", line 23, in <module>
    import unicodedata
ImportError: No module named unicodedata"

**Comment by facelessuser** [comment]
"me too" isn't going to get this fixed, I need someone to confirm that #308 fixes the issue.

**Comment by hkant** [comment]
i fix my problem by the method of commit " b631e1d57221a6a3fec582258e5cfd15d1f855cd":
 from ..util import HTML_PLACEHOLDER_RE, parseBoolValue
 import re
 import logging
-import unicodedata
+try:
+    import unicodedata
+except:
+    import sys
+    from os.path import dirname
+    sys.path.append(dirname(sys.executable))
+    import unicodedata
 
 logger = logging.getLogger('MARKDOWN')

@facelessuser  you modify the file of headerid.py,but there is also a  same problem in the  file of markdown\extensions\toc.py

**Comment by facelessuser** [comment]
@hkant Please see #308.  The link to the commit was only showing what needed to be done to import unicodedata.  Yes I admit that location alone was not enough, but since #308 moves it to be one of the first imports, it should be in the path by time toc or headerid or whatever calls it.

**Comment by facelessuser** [comment]
It is possible we need to place it here as well https://github.com/revolunet/sublimetext-markdown-preview/blob/master/markdown_wrapper.py.

**Comment by facelessuser** [comment]
It actually appears that we should drop this in helper.py as Sublime seems to load them alphabetically.

**Comment by facelessuser** [comment]
#308 has been updated with unicodedata loading in helper.py

**Comment by DannyBen** [comment]
Looks like #308 is working. I just copied the modified files and placed them where they need to be. 

The console now looks clean of errors and the "Markdown Preview" menu items are back.

**Comment by facelessuser** [comment]
Thanks,  I will go ahead and push it out.

**Comment by DannyBen** [comment]
Thanks for the quick fix.
