### ISSUE TITLE
Update README - LiveReload package removed from https://packagecontrol.io/

### ISSUE THREAD

**Issue by ldexterldesign** [revolunet/sublimetext-markdown-preview#314]
Hey,

Thanks for package

https://packagecontrol.io/packages/LiveReload has been removed:

<img width="540" alt="screen shot 2015-12-21 at 02 19 13" src="https://cloud.githubusercontent.com/assets/1715809/11921452/5df9e1ea-a789-11e5-91d2-43dfb9c5ebd7.png">

I suggest you update your README to reflect this (I'm currently attempting to setup https://github.com/vohof/gulp-livereload )

Hope this is useful

Regards

**Comment by pradyunsg** [comment]
I don't think so... https://github.com/alepez/LiveReload-sublimetext3 is linked from there. I guess you took that screenshot when what I presume would have been some shifting period...
