### ISSUE TITLE
GitHub Flavored Markdown stripping inline SVG

### ISSUE THREAD

**Issue by evanplaice** [revolunet/sublimetext-markdown-preview#315]
I like to use Markdown to create design docs including color swatches. With a little SVG I can create a stylish object that displays the swatches.

When I run the Markdown through the GH Flavored Markdown it strips the HTML/SVG tags from the output. The non-GH Markdown parser displays the inline SVG as expected.

Here's an example of the SVG I'm inlining:
```svg
<div>
    <svg width="250" height="50" style="border: 2px solid #888888">
	    <rect x="0" width="50" height="50" style="fill:#302724" />
	    <rect x="50" width="50" height="50" style="fill:#393b44" />
	    <rect x="100" width="50" height="50" style="fill:#fdfeed" />
	    <rect x="150" width="50" height="50" style="fill:#39261d" />
    	<rect x="200" width="50" height="50" style="fill:#c7bda6" />
    </svg>
</div>

*Theme 1*
```

**Comment by facelessuser** [comment]
We don't control the github parser.   We send it to github and they do.  It sounds like they purposely strip it out.  Unless they change how they do things, I guess you're stuck with it.

**Comment by evanplaice** [comment]
@facelessuser :+1: Thanks.
