### ISSUE TITLE
Export "just" HTML code, rather than CSS

### ISSUE THREAD

**Issue by MattDemers** [revolunet/sublimetext-markdown-preview#316]
Sorry if this has been answered, but I'm a Sublime Text newbie and don't really know how to configure the settings to remove the CSS that's generated when I "Copy to Clipboard" in MarkdownPreview.

Is there a way to do this? I'd like similar output to what I get when I "Export CSS in Sublime Text", only to my clipboard; there, I only get the HTML equivalent of the Markdown I highlighted, rather than the associated CSS.

**Comment by cmyr** [comment]
@facelessuser @revolunet would you accept a pull-request if I were to implement this? I'm also interested in implementing something that allows selecting a custom css file.

**Comment by facelessuser** [comment]
You can already use a custom CSS: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L150-L158.

**Comment by cmyr** [comment]
@facelessuser hmm okay. I was imagining implementing it as an option in the dropdown menu when you choose the various 'preview/export' options in the command palette.

how do you feel about the 'no css' option?

**Comment by MattDemers** [comment]
@facelessuser Looking at this, it doesn't really seem to answer my question. I don't want to specify my own CSS; I want _no_ CSS and "naked" HTML for posting into things like blog CMS.

**Comment by cmyr** [comment]
@MattDemers does the `embed_css_for_sublime_output` flag in the settings do what you want?

**Comment by facelessuser** [comment]
@MattDemers I was addressing @cmyr, that is why it didn't answer your question.

In answer to your question, what about: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L219-L226.  Would that option help?

**Comment by facelessuser** [comment]
As there has been no response on this for about a year, I'm going to close this. Reopen if there are still questions on this that need to be addressed.
