### ISSUE TITLE
Github parsing not working properly since update to 1.4.0

### ISSUE THREAD

**Issue by jonjack** [revolunet/sublimetext-markdown-preview#319]
Update: Many apologies, this does not seem to be an issue now. Whatever the issue was seems to have been a temporary problem which now seems resolved. Please close this or let me know if you need a PR.

---

I updated to 1.4.0 today and now Level 2 and 3 headings are not getting parsed/rendered correctly in the Gihtub flavoured style.

---

<img width="937" alt="screen shot 2016-01-20 at 09 31 18" src="https://cloud.githubusercontent.com/assets/604609/12444754/5eacba0e-bf58-11e5-8dbe-c017fc0e499c.png">

**Comment by facelessuser** [comment]
Since we send the content to github via their API to parse the markdown, it was most likely github who were in error.   I can only assume it was a problem with Github's API and only coincedently broke on upgrade to 1.4.0+.

**Comment by jonjack** [comment]
Hi facelessuser. Ye, I would agree that the Github API was likely the glitch. Apoligies for raising the issue.

**Comment by facelessuser** [comment]
No problem,  better to file it and be wrong,  than not file a serious bug.
