### ISSUE TITLE
How to keep the relative path of IMG tags when converting a GFM?

### ISSUE THREAD

**Issue by ThatMrL** [revolunet/sublimetext-markdown-preview#321]
I found that when converting a GFM, relative path of `img` tags will be convert into full path, while relative path of `a` tags will be kept.

The following markdown file

``` markdown
[a link](link/a.html)
![a image](image/b.png)
```
will be converted into something like

```html
<a href="link/a.html">a link</a>
<img alt="a image" src="///C://Documents/image/b.png" />
```

So how to keep the relative path of a image?

**Comment by facelessuser** [comment]
https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L237

Remember this plugin is just for previewing the markdown.  The html output is rendered in a temporary location, so the paths must be adjusted for the sake of the preview.  This gives you an idea of what it will look like, but is not meant to be the final document.

**Comment by facelessuser** [comment]
I am assuming your question was answered?

**Comment by facelessuser** [comment]
Closing as there has been no response.
