### ISSUE TITLE
Allow command line arguments for custom browser

### ISSUE THREAD

**Issue by hannesfrank** [revolunet/sublimetext-markdown-preview#324]
Currently it is not possible to use a browser setting like

``` js
    "browser": "chromium-browser --incognito"
```

because (on my linux system) it is resolved to 

``` python
os.system('"chromium-browser --incognito" /tmp/76.html')
```

I fixed this for myself by changing the command generation from

``` python
cmd = '"%s" %s' % (browser, path)
```

to

``` python
cmd = '%s %s' % (browser, path)
```

which breaks for executable names with whitespaces like `/Applications/Google Chrome Canary.app`.

A more generic solution could be to require the user to quote the whitespace like

``` js
    "browser": "'/Applications/Google Chrome Canary.app' --incognito"
```

But this would probably break some user's settings.

For backwards compatibility you could maybe just quote commands that do not contain a `" -"`, but I'm not sure if I miss something.

**Comment by facelessuser** [comment]
If this is something still desired, please create an issue over at the new supported repo location: https://github.com/facelessuser/MarkdownPreview.
