### ISSUE TITLE
Is there a way to modify page_width?

### ISSUE THREAD

**Issue by AdySan** [revolunet/sublimetext-markdown-preview#325]
The rendered HTML file is rather narrow, I'd like to make it wider. Is there any way I can override the default page width in the markdown file?

**Comment by facelessuser** [comment]
Yes you can override the current CSS in the settings file with what you want.  You can also append a CSS in addition to the default that overrides just the width.

**Comment by facelessuser** [comment]
I am assuming that your question was answered as there has been no response since.  If you still have questions, feel free to ask them here, but I am going to close the issue.

**Comment by AdySan** [comment]
Here's how I got this to work

Modified this line in `MarkdownPreview.sublime-settings`

```
"css": ["default", "C:\\Users\\41atannu\\Downloads\\ady.css"],
```

and `ady.css` looks like this

```
body{
  width: 85%;
}
```

**Comment by facelessuser** [comment]
Looks good!  Thanks for sharing.  This will help others with the same question.
