### ISSUE TITLE
Invalid markdown for html tags with attributes

### ISSUE THREAD

**Issue by dineshbhosale** [revolunet/sublimetext-markdown-preview#326]
I recommend removing all attributes form html tags
Attributes are not included in markdown
Use simple regex like this

`input.replace(/<\s*(\w+).*?>/ig,'')`

this will remove all attributes form all html tags and make markdown more accurate

**Comment by dineshbhosale** [comment]
This code will remove unnecessary stuff from input and make it more accurate

var md=data;

md=md.replace(/\r?\n|\r/g,'');//removing new lines

md=md.replace(/\>\s+?\</ig,'\>\<');//removing blank space between tags

md=md.replace(/.+?\=.+?"?>/ig,'');//removing attributes

var md=toMarkdown(md,{gfm:true});

**Comment by facelessuser** [comment]
What are you trying to solve?
