### ISSUE TITLE
Image dimensions doesn't work

### ISSUE THREAD

**Issue by devkhan** [revolunet/sublimetext-markdown-preview#327]
Markdown:

```markdown
![Alt text](Snapshot.png  =200x50)
```

Generated HTML:

```html
<p>
    <a href="Snapshot.png%20=200x50" target="_blank">
        <img src="Snapshot.png%20=200x50" alt="Image to be placed" style="max-width:100%;">
    </a>
</p>
```

Is this a lacking feature or a bug?

**Comment by facelessuser** [comment]
This is not a feature in the Markdown spec (regardless of what some Markdown parsers might allow).  You could use the Python Markdown attribute extension (also a non-standard feature) to adjust the inline image elements attributes: https://pythonhosted.org/Markdown/extensions/attr_list.html#inline.

**Comment by devkhan** [comment]
Can you please give me some pointer on how to do this? Can it be done by making changes inside the package resources in just my ST installation?

**Comment by facelessuser** [comment]
If you are using the Pyhton Markdown parser (known as `markdown` in the settings), the `attr_list` extension is enabled by default unless you specifically have modified what extensions you are running with in the settings file.  All you have to do is follow the instructions here : https://pythonhosted.org/Markdown/extensions/attr_list.html#inline.  If you are using the Github parser, you are out of luck.
