### ISSUE TITLE
Footnotes and links

### ISSUE THREAD

**Issue by Josca** [revolunet/sublimetext-markdown-preview#328]
I have a problem with markdown parsers. Seems that "markdown" does not support links and "github" parser does not support footnotes. I would like to use both of these features. Can you help me?

I have this markdown text:

# Title
* Text[^fn].
* Link example:
    - [Link text] (http://google.com)

[^fn]: Footnote text.

**Comment by facelessuser** [comment]
1. In your example, your link has a space between the the square and round brackets, remove that and it will probably work for you.

2. Github parser doesn't support footnotes.  I'd say talk to Github because we don't control that :smile:.

**Comment by Josca** [comment]
Oh, you'r right. Thanks :).
