### ISSUE TITLE
Unable to find target command: markdown_build #ST3 #Windows 7 

### ISSUE THREAD

**Issue by henry19922** [revolunet/sublimetext-markdown-preview#329]
i just downloaded the newest version of markdown preview and install as https://github.com/revolunet/sublimetext-markdown-preview#manual-install; but entering "ctrl+shift+p" has no prompt like "markdown preview",  and "ctrl+b" returns "Unable to find target command: markdown_build".
ST3 output below:
> DPI scale: 1
startup, version: 3059 windows x64 channel: stable
executable: /D/Program Files/Sublime Text 3/sublime_text.exe
working dir: /D/Program Files/Sublime Text 3
packages path: /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /D/Program Files/Sublime Text 3/Packages
zip path: /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Installed Packages
found 9 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 3 total files: 164 cache hits: 162
pre session restore time: 0.0929282
startup time: 0.157928
first paint time: 0.159928
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
launching: /D/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
loaded 842 snippets
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin JsFormat-master.js_formatter
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\henrylwu\AppData\Roaming\Sublime Text 3\Packages\Markdown Preview\MarkdownPreview.py", line 14, in <module>
    import yaml
ImportError: No module named 'yaml'
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
plugins loaded
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\henrylwu\AppData\Roaming\Sublime Text 3\Packages\MarkdownEditing\bootstrap.py", line 26, in plugin_loaded
    from package_control import events
ImportError: No module named 'package_control'
Unable to fetch update url contents
Unable to find target command: markdown_build
Unable to open /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Packages/User/MarkdownPreview.sublime-settings

**Comment by facelessuser** [comment]
Looking at your errors, I see MarkdownEditing errors which is a different package than this.  Maybe disable or uninstall that, restart Sublime, and see if you are still getting errors.

**Comment by henry19922** [comment]
after uninstall MarkdownEditing, the issue still exists
ps: Markdown preview is always in the list of "Package Setting" but "Settings - Default" and "Settings - User" are both empty

> DPI scale: 1
startup, version: 3059 windows x64 channel: stable
executable: /D/Program Files/Sublime Text 3/sublime_text.exe
working dir: /D/Program Files/Sublime Text 3
packages path: /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /D/Program Files/Sublime Text 3/Packages
zip path: /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 159 cache hits: 159
pre session restore time: 0.0594369
startup time: 0.112437
first paint time: 0.120437
launching: /D/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin ConvertToUTF8.ConvertToUTF8
loaded 837 snippets
reloading plugin JsFormat-master.js_formatter
plugins loaded
Unable to fetch update url contents
Unable to open /C/Users/henrylwu/AppData/Roaming/Sublime Text 3/Packages/Markdown Preview/MarkdownPreview.sublime-settings

**Comment by facelessuser** [comment]
Something is wrong with your Sublime setup, not the markdown preview package.  The settings load fine on all of my machines.

**Comment by henry19922** [comment]
i reinstalled by package control-install package and it works, thank for your reply
