### ISSUE TITLE
preview side by side like atom.io

### ISSUE THREAD

**Issue by icf20** [revolunet/sublimetext-markdown-preview#330]
is there any way to preview markdown side by side like the markdown package does in atom.io ?

**Comment by facelessuser** [comment]
This isn't going to happen as atom is essentially a web browser which is why it is easy to do side by side.  Sublime can't load HTML in a view and even if it could, the HTML render it uses is too limited.

**Comment by raztd** [comment]
You could do something similar if you install and enable the following extensions: 

[auto-save](https://packagecontrol.io/packages/auto-save)
[LiveReload](https://packagecontrol.io/packages/LiveReload)

**Comment by facelessuser** [comment]
@raztd, yes that is about as close as Sublime can get at the present.  I will close this issue since there is nothing that can be done with Sublime's current API.
