### ISSUE TITLE
This thing is a freaking ghost

### ISSUE THREAD

**Issue by AkelD** [revolunet/sublimetext-markdown-preview#331]
![screenshot 573](https://cloud.githubusercontent.com/assets/13372971/14300638/1fc7df5c-fb68-11e5-8b61-65159cc0ca26.png)
I removed this.
No search engine finds any remain of this.
Why won't this go away.

**Comment by facelessuser** [comment]
I have no idea.  I don't know how you installed it or how you removed it.

**Comment by AkelD** [comment]
@facelessuser First I downloaded the folder. Then I deleted it.

**Comment by facelessuser** [comment]
You've clearly left some files somewhere.  I would check in you `packages` folder and your `installed packages` folder.  This isn't a problem with this plugin, but with something you've done.

**Comment by facelessuser** [comment]
As this is not reproducible, I am closing this issue.
