### ISSUE TITLE
Send to browser but keep sublime text in the foreground optional argument.

### ISSUE THREAD

**Issue by excetara2** [revolunet/sublimetext-markdown-preview#332]
I set up a keybinding to send to browser but prefer if you can have an argument like in `LatexTools` mode that you can choose to keep focus on Sublime or send focus to the browser. If using the `open` command in OSx this should be easy with the `-b` parameter.

**Comment by facelessuser** [comment]
If this is something that is still desired, please create an issue over at https://github.com/facelessuser/MarkdownPreview which will be the new supported location.
