### ISSUE TITLE
paragraph in `<ul>` during conversion

### ISSUE THREAD

**Issue by paul-mesnilgrente** [revolunet/sublimetext-markdown-preview#333]
Hello,

there is a little bug on the conversion of lists. When I write lists, sometimes, the last item is surrounded by `<p></p>`, so it makes a margin between the other items. 

Thank you very much for your work, I love that plugin to take notes in class (especially for the mathjax integration)

**Comment by facelessuser** [comment]
Please provide an example that exhibits the problem so it can be reproduced and confirmed.

**Comment by paul-mesnilgrente** [comment]
Yes sorry, didn't think

```Les tâches
==========

1. Recherche sur la caméra
------------------------------

- Déterminer si elle a une équivalence de l'autobalance des blancs au niveau infrarouge
- Nombre d'image/seconde
- Est-ce qu'il faut la calibrer
- Focale
- Distance caméra - table

2. Recherche sur les objets connectés
-------------------------------------

- précision sur la gestiond de la fréquence
- réactivité de l'accéléromètre

3. Protocole TUIO
-----------------

- vitesse d'émission/réception
- besoin d'une fréquence d'émission ?
- lors du déplacement, coordonnée intermédiaire
```

I use the preview in brower -> github. And the parameters are unchanged apart mathjax.

**Comment by facelessuser** [comment]
Thanks for the info, If you are using the Github parser, you will have to take the issue up with Github as we just send the content to their API and they parse it. I will enter your code below in this comment box so we can see how Github renders it:

Les tâches
==========

1. Recherche sur la caméra
------------------------------

- Déterminer si elle a une équivalence de l'autobalance des blancs au niveau infrarouge
- Nombre d'image/seconde
- Est-ce qu'il faut la calibrer
- Focale
- Distance caméra - table

2. Recherche sur les objets connectés
-------------------------------------

- précision sur la gestiond de la fréquence
- réactivité de l'accéléromètre

3. Protocole TUIO
-----------------

- vitesse d'émission/réception
- besoin d'une fréquence d'émission ?
- lors du déplacement, coordonnée intermédiaire

You can see that Github is the one at fault, not us.

**Comment by facelessuser** [comment]
This appears to not be an issue with Markdown Preview, so I am going to close this.  Hopefully GitHub has or will fix this.
