### ISSUE TITLE
Saving really slow and freezing main window if autoreload enabled on OSx

### ISSUE THREAD

**Issue by excetara2** [revolunet/sublimetext-markdown-preview#334]
If autoreload is enabled the saving the file is really slow taking from maybe 500ms to 2 seconds (Sublime window freeze time) depending and it doesn't release control back to the main Sublime window until it is done so essentially freezes.

Maybe this is because it builds the file everytime and then calls reload and doesn't release back to the window until after? Anyways is there a way to make the reload behavior happen in the background to not affect the main Sublime window.

If not is there a way to trigger the browser to reload with a key-binding instead of on save. So just when I want the browser will reload or parameters to pass to preview so it doesn't always open a new tab. I currently use:
```
    { "keys": ["super+l", "super+m"], "command": "markdown_preview", "args": {"target": "browser", "parser":"github"}, "context": [
      { "key": "selector", "operator": "equal", "operand": "text.html.markdown" }]},
```

**Comment by revolunet** [comment]
If you use `"parser": "markdown"` it should be much faster ? github parser implies a roundtrip to their API

**Comment by excetara2** [comment]
Yes thanks for the tip as that appears to do the trick.

Also is there anything built in for academic referencing like [@Dixon2006]
for example that can be added to the parser?

**Comment by facelessuser** [comment]
There are plugins for the Python Markdown parser that might allow something like this (you would need to verify), but there are none included with Markdown Preview by default.

**Comment by excetara2** [comment]
Okay thanks. I've found something and the plug in works fine now.
