### ISSUE TITLE
Anchor tags

### ISSUE THREAD

**Issue by chartre** [revolunet/sublimetext-markdown-preview#337]
The anchor tags automatically created for each header have prepended the text `user-content-`
IDK if this is the espected behaviour or is an issue. I'm new to md and html and this situation made me lost some time because in [this](http://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown) stackoverflow question (and others), most voted answers says that the tag and header text should be almost equals.

Any thoughts on this?

**Comment by facelessuser** [comment]
This was mentioned recently on a closed issue. This affects only the **github** parser and not the **markdown** parser (Python Markdown).  `user-content` isn't specifically the problem.  The problem is that Github changed how they generate their ids and such.  I don't recall the exact issue, but it needs to be reworked due to Github's recent changes.

**Comment by chartre** [comment]
Hi and thanks to the fast answer.
Well, I was checking the parser options and I'm using the defaults, so the parser should be the python-markdown as the comment states. 

> default - The current default parser is python-markdown parser.

The results using either `Markdown Preview: Preview in browser` or the output from `Build`, are the same, the "issue" there.

Maybe this doesn't worth to spend time on it, but I can make tests and post results if you want.

**Comment by chartre** [comment]
Reopening (closed by mistake)

**Comment by facelessuser** [comment]
I am aware that the GitHub anchor have a problem which is why I mentioned then.

Are you having issues with Python Markdown?  Or are you just confused at the output?  I'm not sure yet what this issue is about.

**Comment by facelessuser** [comment]
So this is what Python Markdown does for me:

```
<h3 id="unicode-properties"><a name="user-content-unicode-properties" href="#unicode-properties"
```

This is expected.  The header tag unique id  is `unicode-properties`.  The anchor tag's href is `unicode-properties`, so when you click it, it will take you to the `h3` tag with the same unique id.  The name prepends `user-content`, and that is fine, it is just a name.

In Github it is currently messed up, but I will not go into that.  Hopefully this answers your question.

**Comment by chartre** [comment]
Ok, in some point I messed with what the ST3 was outputting.
Let me explain a bit so it gets clear what happened and can close this:

I was looking for a way to make internal references to sections inside the document, so I came to some place in google and started to create the reference calls in the way `[text](#header-in-lower-case)`. But with the option `Markdown Preview: Preview in browser` + `github`, they didn't work.
Then I came to the stackoverflow question posted above and I learned about the `anchor tags`. Digging in the html output I saw the `user-content-` thing so I though that it was the problem and then, came here with the intention to help with a possible bug/issue.
But now that you explained that the `github` option may not work as expected, I tested other ways to obtain the html ( `Markdown Preview: Preview in browser` + `markdown`, or just build the md) and they work well.

At this point now it is clear and I apologize to make you waste your time.
Thanks for all.

**Comment by facelessuser** [comment]
No biggie.  GitHub needs to get fixed.  I just haven't had time to touch it.

**Comment by facelessuser** [comment]
Is this still a problem?  I am actually having difficulties reproducing this issue now, but I remember I used to be able to reproduce the issue.  Maybe Github changed things again.

With the following set I am not seeing the issue with github:

```js
"github_mode": "markdown",
```

If you set it to:

```js
"github_mode": "gfm",
```

You won't have clickable links, but it has always been that way as Github's API doesn't generate any ids for headers in `gfm` mode for some reason.

**Comment by chartre** [comment]
No changes for me. Default options (`"github_mode": "markdown"`) and "Preview in browser: github" makes the issue there.
Maybe some package has been updated? Mine are:
Markdown Preview v 1.4.0
Package Control v 3.1.2
ST3 build 3103

**Comment by khamaileon** [comment]
+1

**Comment by facelessuser** [comment]
I will double check a couple of my systems and fix if can reproduce.  I'm looking to get this closed out.

**Comment by facelessuser** [comment]
I am on:

ST3 dev build 3113 (equivalent to beta 3114)
Markdown Preview 1.4

I just tried this again and anchor tags are working.  Do you have the following enabled:

```js
    "github_mode": "markdown",
    "github_inject_header_ids": true,
```

We have to actually inject header ids into the headers as Github doesn't do it themselves for some odd reason.  `github_inject_header_ids` is a workaround that injects the headers the same way supposedly does on their site.  Try the settings above and please report back.  I think in general we are correctly generating the headers correctly, but if you find a case where we don't generate and inject the header properly, let me know, but whatever I saw before, I am not seeing now.  Everything looks like it is working.

**Comment by chartre** [comment]
There is the reason. The default options are:
```
"github_mode": "markdown",
"github_inject_header_ids": false,
```
Changing to
```
"github_inject_header_ids": true
```
the issue is gone.

**Comment by facelessuser** [comment]
I will consider this issue closed then.
