### ISSUE TITLE
may i modify the markdown.css

### ISSUE THREAD

**Issue by visoeclipse** [revolunet/sublimetext-markdown-preview#344]
when i change the markdown.css  
```code
width: 45em   =>  width: 80%
```
then, i can not use markdown-preview again.

in mac 10.11
sublime 3103

**Comment by visoeclipse** [comment]
any body can help me ?  thx

**Comment by revolunet** [comment]
whats happening exactly when you try to use the plugin ?
can you try menu view -> show console to find something revelant here ?

**Comment by revolunet** [comment]
btw of course you can edit the css. but if you update the plugin it will be overwritten.
you can speciify alternate css file in the plugin preferences

**Comment by visoeclipse** [comment]
yes,
```code
 alternate css file in the plugin preferences
```

thank u very much,  thanks
