### ISSUE TITLE
LiveReload Plugin not available anymore

### ISSUE THREAD

**Issue by LeonardoGentile** [revolunet/sublimetext-markdown-preview#347]
Salut Julien :)
I've been using the plugin for a while, but recently I've switched to a new plain installation of ST3, and when I've tried to pair it with the [livereload](https://github.com/dz0ny/LiveReload-sublimetext2) plugin I've found out it is not available anymore. 

There are other livereload plugins available for ST, for example https://github.com/alepez/LiveReload-sublimetext3 but I had no luck in making things work correctly.

Any basic example or an alternative on how to use another livereload option? Maybe browsersync or is it an overkill?

**Comment by facelessuser** [comment]
If I get some time, I may look into it.

**Comment by revolunet** [comment]
Hey Leonardo :) Sorry for the delay, hope everything is fine where you are.

In the palette, try to select : "LiveReload: enable on save" ? i had to do this too

**Comment by zachatrocity** [comment]
The suggestion by @revolunet resolves this issue.

1. Open Palette
2. LiveReload: Enable/Disable Plugins
2. Enable Simple Reload.

This issue can probably be closed.

**Comment by LeonardoGentile** [comment]
@revolunet salut, yes everything is ok, still I'm there :)
Thanks also to @zachatrocity. These are the steps to make things work.

- Install the "new" livereload package: https://github.com/alepez/LiveReload-sublimetext3
- On a markdown file open the command palette and select `Markdown Preview: Preview in Browser`
- Open the command palette again and `LiveReload: Enable/Disable Plugins`
  - Enable Simple Reload

Then start to work on the file.

**Comment by jdhao** [comment]
For newcomers to this issue.  @LeonardoGentile's way works, but I find that If you quit sublime text and the next time you use it, your settings for livereload will not be remembered.  You have to enable the `Simple Reload` plugin again. 

To make this setting permanent, we can edit the LiveReload user setting and add the following:
```
{
"enabled_plugins": [
   "SimpleReloadPlugin",
   "SimpleRefresh"
]
}
```

Then we do not need to enable LiveReload plugin every time we restart sublime text.
