### ISSUE TITLE
Indentation of whole document with Markdown (vs MultiMarkdown) syntax

### ISSUE THREAD

**Issue by setempler** [revolunet/sublimetext-markdown-preview#348]
Hi,

after installing Markdown Preview (via Package Control), the whole content of a `Markdown` syntax displayed file is indented.

![issue01](https://cloud.githubusercontent.com/assets/3781869/16799020/19bc0c62-48ef-11e6-8f6c-89964dee25c9.png)

This does not appear, when syntax is set to `MultiMarkdown`:

![issue02](https://cloud.githubusercontent.com/assets/3781869/16799041/2c5438a4-48ef-11e6-8b19-eab5b3a26af0.png)

After uninstalling, the problem remains.

I am running build 3114 on OSX 10.11.5. My user config is:

```js
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Theme - Dark Material/schemes/Dark-Material.tmTheme",
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"overlay_scroll_bars": "enabled",
	"remember_open_files": false,
	"rulers":
	[
		100
	],
	"show_encoding": true,
	"tab_size": 4,
	"theme": "Dark-Material.sublime-theme"
}
```

Thanks for any hints!

**Comment by facelessuser** [comment]
This plugin doesn't modify how markdown is displayed in Sublime.  I would double check all your other installed plugins and all of your settings.

**Comment by setempler** [comment]
Thanks, I now set `MultiMarkdown` as default for markdown files, and am OK with that.
