### ISSUE TITLE
latex equation align

### ISSUE THREAD

**Issue by entron** [revolunet/sublimetext-markdown-preview#350]
I noticed that the latex command `align` is not rendered correctly. For example:

```
$$
\begin{align} 
2x - 5y &=  8 \\ 
3x + 9y &=  -12
\end{align}
$$
```

We show two equations in two lines, but markdown-preview only shows them in one line.

**Comment by facelessuser** [comment]
You are responsible for escaping things appropriately as we don't have a proper plugin including to preserve syntax and such.  You need to escape the slash, but since Markdown gets a hold of it, it removes one of the escapes, so you have to double escape it:

```
$$
\begin{align} 
2x - 5y &= 8 \\\\ 
3x + 9y &= -12
\end{align}
$$
```

**Comment by entron** [comment]
Thanks for the workaround! Though I am still hoping, sublimetext can parse the standard algin notation some day to make things easier.

**Comment by facelessuser** [comment]
It's not SublimeText, it is specifically a Markdown and LaTeX conflict.  We include no actual extension in this plugin to parse LaTeX style math.  People do what you do and include LaTeX style math and hope it gets through the Markdown converter unaltered, and **then** MathJax gets applied.  You would need a Python Markdown extension like I wrote here that preserves the content: http://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/.  

```
$$
\begin{align} 
2x - 5y &= 8 \\
3x + 9y &= -12
\end{align}
$$
```

Now you may notice that I still have to escape the newline, but it is less severe.  It has to do with when it gets handled in the Markdown process.  I handle it before other inline/block processes, but not before escaped newlines.  To do that, I would have to process the entire plain text file before all other processing **and** avoid fenced blocks **and** indented code blocks.  Not fun. I wrote the extension included in this plugin which handles nested fenced blocks.  You can look at the coding gymnastics I had to do to get that to work: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/markdown/extensions/superfences.py.  I opted for something more simple for math, so you have to at least escape your escaped newline.  This is no different than some other Markdown/LaTeX implementations: http://meta.math.stackexchange.com/a/3526.

Anyways, why haven't I already added the extension here?  I don't really maintain this plugin, and I am using it less and less.  So supporting my extensions in two places is exhausting.  I just kind of drew a line and told myself I wasn't going to port anything else over here.  Anyone else is free to, but I am kind of backing off stuff here.  I maintain too much stuff as is.

**Comment by entron** [comment]
hi @facelessuser, thank you very much for the explanation! I really appreciate all the intense work involved in building and improving this excellent plugin. Actually, I have been searching a good markdown solution on linux for years and this plugin is the best made in my opinion.

Back to the problem, I noticed that in my original post I forgot to use code block, so the line breaks was displayed as `\` instead of `\\`. `\\` is the correct latex way to do line break in latex, and arithmatex already handles it correctly.

**Comment by facelessuser** [comment]
Cool, good to know.  I only use the LaTeX math stuff on occasions, so I can never remember all the syntax.
