### ISSUE TITLE
Preview opening an empty browser window

### ISSUE THREAD

**Issue by marcingrabda** [revolunet/sublimetext-markdown-preview#353]
With the latest version of Sublime and the plugin preview is opening an empty page. I can provide details if needed.

Regards,
Marcin

**Comment by facelessuser** [comment]
Unfortunately, this is not an issue I'm seeing.  I imagine this was a user configuration issue. I imagine you got this working as it's been over a year. Sorry, someone didn't get to this issue sooner.  I'm going to close this, but open again if you are still having issues.
