### ISSUE TITLE
launching default browser failed in ubuntu, how to debug

### ISSUE THREAD

**Issue by smilingsun** [revolunet/sublimetext-markdown-preview#354]
I've looked into some other issues, but couldn't find relevant information, so I create this issue.

I'm working in Ubuntu 15.10, with Sublime Text Build 3114.

When I click **Markdown preview: preview in the browser**, and choose either **github** or **markdown**,  then the line **markdown preview launched in default browser**  stays in the left-bottom corner for seconds, and nothing happens.

**Comment by facelessuser** [comment]
I would need more info to look into this.  Are they errors in the console? What are your user settings? Sublime version? Etc.

**Comment by smilingsun** [comment]
My working operating system is back to Windows, so sadly I cannot reproduce it now.
So sorry and you can close this issue. Thanks.

**Comment by monoflo** [comment]
I am having this same issue, and it has consistently occurred for me.
How can I help?

**Comment by monoflo** [comment]
Sublime Text: Stable Channel, Build 3126

**Comment by facelessuser** [comment]
@monoflo, are you on Linux?  And if so, are HTML assigned to open by default in a different app in your OS?

**Comment by monoflo** [comment]
Yes, I'm using a Linux-based OS.
The OS' default browser is Google Chrome, but I use Firefox.

I realized that Firefox wasn't my default browser, so changing that solved the problem. I changed it the default back to Chrome and it also works.

Problem fixed 👍

**Comment by facelessuser** [comment]
To any others that have this issue, behind the scenes, almost all Linux OSs well open the HTML  via xdg-open in this plugin to get the default application associated with HTML. So if that doesn't open HTML properly, most likely something needs to be done on your system instead of the plugin.

@monoflo glad you figured out what needed to be done.
