### ISSUE TITLE
If several parsers enabled how to select needed?

### ISSUE THREAD

**Issue by kiddick** [revolunet/sublimetext-markdown-preview#355]
I have some files with `.md` and `.rst` formats.
Is it possible to bind parsers by extension?

**Comment by facelessuser** [comment]
I know this has been open for a while, but Markdown Preview does not support `.rst` format.  It is not meant nor planned to support `.rst` format. 

Now to answer the question about whether a parser can be bound to a specific extension; this doesn't really make sense when the only type of document you parse is Markdown.  I personally have no interest in this feature, and sense there has been no comments from anyone else on this project, I suspect there is no interest from other contributors.

I will close this issue as there is no actionable item.
