### ISSUE TITLE
Enable html tags inside the markdown file

### ISSUE THREAD

**Issue by alecive** [revolunet/sublimetext-markdown-preview#357]
Hello, 

I don't know if this works already but I didn't manage to make it work: I would like to add some html tags inside my markdown files so that I can add custom styling and settings. Right now, everything that is inside the html is not parsed by the parser any more. Would this be possible?

I would like for example to have this working:

```
<div style="text-align:center;">
![Caption](img url)
<p style="font-size: 1.2em;">Caption</p>
</div>
```

**Comment by facelessuser** [comment]
If you are using the Python Markdown parser, this is already possible with the `extra` extension.  You simply create your block HTML tags with the attribute `markdown="1"`.  You are tough out of luck if you are using the Github parser as we don't control the Github parser; we simply send your content to them via their API and they return the result.

**Comment by alecive** [comment]
Oh, this is great! Thank you for the tip!
