### ISSUE TITLE
matrix notation in asciimath not rendered

### ISSUE THREAD

**Issue by dracodoc** [revolunet/sublimetext-markdown-preview#358]
I enabled mathjax, and asciimath notation can be rendered properly in preview. However the matrix notation is not rendered correctly.

Input this in [asciimath website preview](http://asciimath.org/)

    ((F_1), (F_2)) = ((0,1), (1,1)) * (F_0, F_1)

It's a matrix form. However this in sublime with markdown preview doesn't show the matrix.

    $$((F_1), (F_2)) = ((0,1), (1,1)) * (F_0, F_1)$$

**Comment by facelessuser** [comment]
This does not support that notation.  MathJax is what is used, and it is not configured to support asciimath .  See MathJax documentation or google search for MathJax syntax.  Maybe you could  configure your own [HTML template](https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L169) or and configure it for [asciimath](http://docs.mathjax.org/en/latest/asciimath.html).

**Comment by dracodoc** [comment]
I think [MathJax included asciimath](http://docs.mathjax.org/en/latest/asciimath.html), and the [asciimath website recommended this usage](http://asciimath.org/).

**Comment by facelessuser** [comment]
Notice we are not adding `asciimathml.js`: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/mathjax.html#L13.  And we don't use this either: `<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML"></script>`.

**Comment by dracodoc** [comment]
OK, got it. I'll try to customize mathjax or use html template.
