### ISSUE TITLE
Need to have internet access when doing enable_mathjax=true

### ISSUE THREAD

**Issue by albertcthomas** [revolunet/sublimetext-markdown-preview#360]
Hi,

Last wednesday, I wanted to enable mathjax for the first time. So I set enable_mathjax=true. But it was not working when previewing the file in my browser.
I finally found that it was because I didn't have an internet access at the time and that I needed to have internet access for mathjax to download in the background. I found this information on [Timon Wong's blog](http://theo.im/blog/2012/11/03/latex-support-in-omnimarkuppreviewer/).

I think it could be a good thing to add it in the README, after the small example in Mathjax support.
What do you think?

I can do the PR if you want.

Albert

**Comment by facelessuser** [comment]
I think that sounds reasonable.  I think a pull request would help others.

**Comment by jrappen** [comment]
@albertcthomas please close this
