### ISSUE TITLE
auto reload not work , have to refresh

### ISSUE THREAD

**Issue by eromoe** [revolunet/sublimetext-markdown-preview#362]
sublime 3 , win 8.1,   not work on both ie and ff.

It doesn't auto refresh page, even if I save my file. I have to refresh browser myself.

usersettings:

```
{
    "parser": "markdown",
    "enabled_parsers": ["markdown"]
}
```

PS:I found `OmniMarkupPreviewer` use a local server to achieve that .

**Comment by revolunet** [comment]
Hi, can you please check this issue : https://github.com/revolunet/sublimetext-markdown-preview/issues/347 

and tell me if it works for you ?

Cheers

**Comment by eromoe** [comment]
It only works on save. 
How to make page change when I change the file without save?

**Comment by facelessuser** [comment]
Please see #389 for information regarding this bug.  I believe a solution is close.  To cut down on duplicate issues, I am closing this.  Please redirect comments to #389.
