### ISSUE TITLE
[Bug] Incorrect anchors conversion 

### ISSUE THREAD

**Issue by Kristinita** [revolunet/sublimetext-markdown-preview#364]
### Summary

When I convert Markdown to HTML use MarkdownEditing, anchor links in file converted incorrect.

### Expected behavior

I have markdown file:

```markdown
1. [Description](#description)
1. [Support](#support)
    1. [Platforms](#platforms)
    1. [Sublime Text](#sublime-text)

## Support

### Platforms

Windows, macOS, Linux.

```

When I convert this file to HTML, I get:

```html
<ol>
    <li><a href="#description">Description</a></li>
    <li><a href="#support">Support</a>
        <ol>
            <li><a href="#platforms">Platforms</a></li>
            <li><a href="#sublime-text">Sublime Text</a></li>
        </ol>
</ol>
<h2 id="support">Support</h2>
<h3 id="platforms">Platforms</h3>
<p>Windows, macOS, Linux.</p>
```

### Actual behavior

Very bad conversion.

```html
<ol>
<li><a href="#description">Description</a></li>
<li><a href="#support">Support</a><ol>
<li><a href="#platforms">Platforms</a></li>
<li><a href="#sublime-text">Sublime Text</a></li>
</ol>
</li>
</ol>
<h2><a name="user-content-support" href="#support" aria-hidden="true"><span></span></a>Support</h2>
<h3><a name="user-content-platforms" href="#platforms" aria-hidden="true"><span></span></a>Platforms</h3>
<p>Windows, macOS, Linux.</p>
```

### Steps to reproduce

I open my markdown file → in the tab where open my Markdown file, <kbd>Ctrl+Shift+P</kbd> → `Markdown Preview: Export HTML In Sublime Text` → `markdown` → I get results for actual behavior, not for expected behavior. 

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by facelessuser** [comment]
It is always helpful to also detail the issue.  I am assuming you are concerned that there is no ids?  Are you using default settings?  It is likely if it is ids that you don't have something enabled.  The underlying parser for the "markdown" parser (not the "github") parser is  Python Markdown.  As far as I know, there is no issue with id translation in the version being used, but you must enable the extension that creates the ids.  I would first need to be sure what the settings you are using.

**Comment by Kristinita** [comment]
@facelessuser, my `User/MarkdownPreview.sublime-settings` file.

```json
{
	"html_simple": true
}
```

I not change value of `parser` parameter for me.

**Comment by facelessuser** [comment]
`html_simple` strips out ids, classes, and styles to give mainly just the tags.  I guess, ids could be allowed in the future, and other attributes could be added, or maybe the attributes that get stripped could be configured.  It's not a bad conversion, it is simply what you are asking for when enabling `html_simple` in its current form.

The added anchor wrapping is due to one of the enabled extensions, probably `headeranchors` which is included when the `github` extension is added: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L99.  You can disable the `github` extension in the settings file, and manually add the ones you want (see the readme for all the 3rd party extensions).

**Comment by Kristinita** [comment]
All right, now my MarkdownPreview.sublime-settings file is:

```json
{
    "html_simple": false,
    "embed_css_for_sublime_output": false,
}
```

Conversion:

```html
<ol>
    <li><a href="#description">Description</a></li>
    <li><a href="#support">Support</a>
        <ol>
            <li><a href="#platforms">Platforms</a></li>
            <li><a href="#sublime-text">Sublime Text</a></li>
        </ol>
    </li>
</ol>
<h2 id="support"><a name="user-content-support" href="#support" class="headeranchor-link" aria-hidden="true"><span class="headeranchor"></span></a>Support</h2>
<h3 id="platforms"><a name="user-content-platforms" href="#platforms" class="headeranchor-link" aria-hidden="true"><span class="headeranchor"></span></a>Platforms</h3>
<p>Windows, macOS, Linux.</p>
```

I get many unnecessary attributes. How I can get expected behavior?

```html
<ol>
    <li><a href="#description">Description</a></li>
    <li><a href="#support">Support</a>
        <ol>
            <li><a href="#platforms">Platforms</a></li>
            <li><a href="#sublime-text">Sublime Text</a></li>
        </ol>
</ol>
<h2 id="support">Support</h2>
<h3 id="platforms">Platforms</h3>
<p>Windows, macOS, Linux.</p>
```

Thanks.

**Comment by facelessuser** [comment]
As I mentioned before, you will need to specify the extensions you want.  The `github` extension includes numerous extensions, one of which is called `headeranchor` which is responsible for inserting the extra HTML.  It inserts them so you get the anchor link that appears when you mouse of the header (with the appropriate CSS) like what happens in Github.  I gave you the link https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L99 which points the setting that controls the extensions.  The extensions are only used when you use the `markdown` parser, not the `github` parser.

**Comment by Kristinita** [comment]
@facelessuser , I don't understand, **how** I can disable `github` parser. I can disable github parser in settings or I need to create YAML file?

Thanks.

**Comment by facelessuser** [comment]
Start by adding this in your user settings:

```js
 /*
        List of enabled extensions of the selected markdown parser.
        You can get the full list of extensions at:
            * The python markdown parser, the `markdown`: http://pythonhosted.org/Markdown/extensions/index.html
        default - use the default set of extensions, see table later.
        [ "default", "def_list", ... ] - a list of extensions. Use "default" to include the default extensions.
            Parser     | "default" Values
        ------------|---------------------------
            default    | ["extra", "github", "toc", "meta", "sane_lists", "smarty", "wikilinks"]
            markdown   | ["extra", "github", "toc", "meta", "sane_lists", "smarty", "wikilinks"]
            github     | extension's values are not used.
    */
    "enabled_extensions": ["extra", "toc", "meta", "sane_lists", "smarty", "wikilinks"],
```

Notice I removed `github`.  Github adds a number of extensions to give a Github Markdown feel: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/markdown/extensions/github.py#L4-L12.  If you follow the link, you can see which extensions are added.  `headeranchor` is the one responsible for the additional elements and classes you are not interested in.  If you want to add the extensions listed, you can those back in instead of specifying `github`.

```js
    "enabled_extensions": ["extra", "toc", "delete",  "githubemoji", "magiclink", "tasklist", "superfences",  "nl2br", "meta", "sane_lists", "smarty", "wikilinks"],
```

You can remove or add whichever ones you dislike or like respectively.

Hopefully that makes it a little more clear.

**Comment by Kristinita** [comment]
Thank you very much!

**Comment by Kristinita** [comment]
@facelessuser , what is `delete` extension? I'm not find this extension in lists [Official supported extensions](http://pythonhosted.org/Markdown/extensions/index.html#officially-supported-extensions) and [Third Party Extensions](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions).

Thanks.

**Comment by AckerApple** [comment]
Hey its 2017, and if you like myself, tried everything recommended in this issue: You just need to see this issue: https://github.com/revolunet/sublimetext-markdown-preview/issues/337

The key is to add to user settings, the following,
```
"github_inject_header_ids": true
```
