### ISSUE TITLE
Not taking to browser 

### ISSUE THREAD

**Issue by VoLuong** [revolunet/sublimetext-markdown-preview#365]
I am on :
- Ubuntu 16.04 LTS
- Sublime Stable Channel, Build 3126
- Markdown Preview Package version 1.4.0  

---

My problem is :

**It just doesnt take me to the browser. When I choose preview in browser either with github flavoured or standard markdown, it creates another .html file in sublime instead of taking me to the browser like before. It is also notable that this .html file, when viewed, show exactly the content of my markdown file.**  

---

An image description : 

![image](https://cloud.githubusercontent.com/assets/15828926/19303972/fb6bdbdc-9094-11e6-9631-9834047d85bb.png)

---

What I have tried : 
- Reinstall plugin
- Restart Sublime
- Reinstall Sublime

---

What I wish for : 

> being able to make this plugin functional again

**Comment by buenahora** [comment]
Having the same issue. Building does not launch the browser

**Comment by buenahora** [comment]
You have to set `"build_action": "browser"` in your user settings!
