### ISSUE TITLE
Enable auto-close for `code tags`

### ISSUE THREAD

**Issue by FloEdelmann** [revolunet/sublimetext-markdown-preview#372]
Enable auto-close for `code tags` ('`').

You can look into https://github.com/randy3k/LaTeXBox/blob/master/support/Default.sublime-keymap#L393 to see how `$` auto-closing is handled there.

**Comment by facelessuser** [comment]
This is not a plugin to help with writing Markdown, it is simply a plugin to preview Markdown.

**Comment by facelessuser** [comment]
I will close this as this issue is not related to the goal of MarkdownPreview.
