### ISSUE TITLE
installing stop in error

### ISSUE THREAD

**Issue by wy7980** [revolunet/sublimetext-markdown-preview#373]
when install sublimetext-markdown-preview console show the following message:
Package Control: No updated packages
ignored packages updated to: ["Markdown Preview"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...

stop in installing, so I can not install in package control. Then I tried to install manually but it can not display correctly in browser.

**Comment by facelessuser** [comment]
So it never installs the `pygments` package?

**Comment by wy7980** [comment]
I have installed markdown preview before, so there have been a `pygments` package. It can be installed now after I reboot my computer. thx !

**Comment by facelessuser** [comment]
I'm glad you got it to install.  I will go ahead and close this issue then.
