### ISSUE TITLE
citation integration via bibtex

### ISSUE THREAD

**Issue by tobiasgerstenberg** [revolunet/sublimetext-markdown-preview#375]
I was wondering whether there is a way of getting references to display correctly in the generated html file. I'm not sure whether sublime-markdown-preview uses pandoc to generate the html from the markdown file. If so, it would be great if it was possible to update the pandoc command so as to include a reference to a bibtex file.

**Comment by facelessuser** [comment]
Nope, doesn't use pandoc.  Not sure which Markdown parser you are using (github or markdown), but if it is GitHub, you get what GitHub returns as we use their API.   If you are using the markdown (Python Markdown) parser, it can be extended with custom extensions.  You'd have to write your own and then add it in the settings appropriately.

**Comment by tobiasgerstenberg** [comment]
ok, thanks! if this feature could be implemented in a way that's easy to use, that would be great.

**Comment by facelessuser** [comment]
This seems out of scope, but possible for a 3rd party to do.  I'll go ahead and close.
