### ISSUE TITLE
LiveReload does not work in ST3

### ISSUE THREAD

**Issue by vasekch** [revolunet/sublimetext-markdown-preview#376]
main README.md says: "Browser preview auto reload on save if you have the ST2 LiveReload plugin installed." the link https://github.com/dz0ny/LiveReload-sublimetext2 is broken.

I have ST3, so I installed following similar plugin

![image](https://cloud.githubusercontent.com/assets/2572537/21939593/cbe4933e-d9c0-11e6-8430-950bf0a830de.png)

After rendering a .md file I see LiveReload started in ST3 console

```
INFO:WebSocketClient:new client ('127.0.0.1', 44686)
INFO:WebSocketClient:new client ('127.0.0.1', 44688)
INFO:WebSocketClient:Add to clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x7fc474e0ff10>
INFO:WebSocketClient:{'length': 151, 'payload': b'{"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","snipver":"1"}', 'mask': b'\xd2i\xea\xc2', 'hlen': 4, 'left': 0, 'opcode': 1, 'close_reason': None, 'close_code': None, 'fin': 1}
INFO:WebSocketClient:Command: hello
INFO:WebSocketClient:{'length': 100, 'payload': b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///tmp/107.html"}', 'mask': b'\x91\x13?\x88', 'hlen': 2, 'left': 0, 'opcode': 1, 'close_reason': None, 'close_code': None, 'fin': 1}
INFO:WebSocketClient:Command: info
b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///tmp/107.html"}'
```

I can see opened socket in browser as well.

But when I do some changes in .md file and save, browser is not reloaded.

I also tried to server file on localhost:8000/107.html to avoid cross-origin issues, but no luck.

I'd appreciate any help.

**Comment by dericcrago** [comment]
Hi @vasekch - have you tried using the resolution mentioned in #347 ?

**Comment by clinei** [comment]
The "Simple Reload" plugin from the should automatically be enabled by Markdown Preview.
It requires LiveReload to be installed first.

**Comment by jhogan4288** [comment]
@clinei, your proposed solution fix the issue for you?  I played with "enable_autoreload" but didn't get anything to work there either.  

I couldn't quite understand what the setting is intended to do, but it seems like the issue I'm seeing (in #388) is from the .html file not being regenerated, rather than the browser page not being reloaded.

**Comment by clinei** [comment]
@jhogan4288, sadly no, need to look into this more

**Comment by revolunet** [comment]
Hi, sorry for this !

We changed the default `enable_autoreload` to false recently (security reasons). so you now have to explicit set `enable_autoreload: true` in your settings. Can you confirm it works for you ?

If not there may be an exception. You can find it in "view > console" and report it here. 

Thanks

**Comment by clinei** [comment]
I did the aforementioned things, but the trouble seems to be within LiveReload:
```
ERROR:WebSocketClient:Decoding error
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Sublime Text 3\Packages\LiveReload\server\WebSocketClient.py", line 56, in __init__
    self.headers = self.wsh.headers
AttributeError: 'WSRequestHandler' object has no attribute 'headers'
INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x0000003FAD15E470>
```

**Comment by revolunet** [comment]
maybe check this comment : https://github.com/revolunet/sublimetext-markdown-preview/issues/389#issuecomment-301921456

**Comment by clinei** [comment]
@revolunet Yup, that specific order worked. Most likely I enabled the SimpleReload plugin before doing the restart after installing LiveReload.

**Comment by facelessuser** [comment]
I will close this in favor of #389, but this issue is more complicated than described.  I will be making a change to livereload script insertion to overcome issues specifically with recent Chrome versions.  Also, it may be good to use the `Simple Reload with delay` option as I found without it I was one rev behind, this may be machine dependent, so maybe `Simple Reload` is all that is needed.

Please redirect discussion of this issue to #389.
