### ISSUE TITLE
Add support of `SmartSymbols`

### ISSUE THREAD

**Issue by ihodev** [revolunet/sublimetext-markdown-preview#378]
Hello there! Could you add the support of the [SmartSymbols](http://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/) extension, I really like it much :heart_eyes: 

Thanks!

**Comment by facelessuser** [comment]
I'd bring over more of those plugins, but it is always a pain porting them over here.  I wish this plugin would drop ST2 moving forward, then I could just add pymdown-extensions as a dependency.  But as it is now, I have to port them over and ensure that anything I bring has Python 2.6 support, which pymdown-extensions doesn't do out of the box.  It's why some of the extensions here are behind .

**Comment by facelessuser** [comment]
I may be able to get this in.  I'm working towards helping to drop ST2 support and pulling all the stuff via dependencies.

**Comment by facelessuser** [comment]
This is working on the dev branch now, but that branch is unstable right now as I am refactoring and changing how things work.  But this will definitely be in 2.0.

**Comment by facelessuser** [comment]
This will be covered by #393
