### ISSUE TITLE
Autoreload is always one build behind

### ISSUE THREAD

**Issue by matthew-groth** [revolunet/sublimetext-markdown-preview#383]
Just installed with LiveReload and everything is up and running with the LiveReload Chrome extension. Only problem is for some reason the HTML displayed in my browser is always one build behind, so I only see the changes I made before 2 builds ago instead of the last build. If I refresh my browser, it catches up and loads the latest changes. I suspect this plugin may trigger the browser to reload _before_ it builds the latest HTML.

**Comment by facelessuser** [comment]
Please see comments in issue #389.  All autoreload discussion will be done there.  I have run into both no autoreload and reload a revision behind, and I believe I have a solution, check out #389 to read more.  In short, I would try using LiveReload's `Simple Reload with delay (400ms)`.  But there are more issues on even later versions of Chrome, but I should have a fix for that.

Anyways, I will close this issue in favor of #389 to cut down on duplicates. Please redirect further dialog on this there.
