### ISSUE TITLE
Navigation to preview another Markdown file

### ISSUE THREAD

**Issue by dtrofimov** [revolunet/sublimetext-markdown-preview#385]
I have a personal wiki with Markdown notes, having relative references to each other. When I preview a note with Markdown Preview and try to navigate to another note, I'm getting this file opened in my browser as a Markdown source.

I'd like to automate this navigation to open a second note in Markdown Preview as well. I have managed to override `onclick` handler across the document, but the logic to build the new preview should happen on Sublime side. So I need to call back to Sublime, to pass the desired file URL, and to automate calling Markdown Preview for this opened file.

Is this possible within the current architecture of the plugin?

**Comment by facelessuser** [comment]
I am taking owner ship of this moving forward over at https://github.com/facelessuser/MarkdownPreview.  I have no intentions at this time of implementing links that call back to Sublime and cause building of other pages.

Closing this issue as there is no plans to implement this at this time.
