### ISSUE TITLE
MathJax src points to retired CDN

### ISSUE THREAD

**Issue by bokrosbalint** [revolunet/sublimetext-markdown-preview#386]
The MathJax CDN hosted at cdn.mathjax.org shut down on April 30, 2017. Please migrate to another CDN according to [this article][1] in the extension.

[1]: https://www.mathjax.org/cdn-shutting-down/

**Comment by revolunet** [comment]
thanks for reporting, just submitted a PR

**Comment by yxliang01** [comment]
Please update the `packagecontrol.io` package soon. Since everything breaks now.

Thanks

**Comment by revolunet** [comment]
should be ok ?

**Comment by yxliang01** [comment]
Great! Thanks. Will try soon. You may close this now. If there's still issue. I will comment here again.
Thank you for making this great!
