### ISSUE TITLE
Preview not refreshing w/LiveReload

### ISSUE THREAD

**Issue by jhogan4288** [revolunet/sublimetext-markdown-preview#388]
I've followed the steps in [#347](https://github.com/revolunet/sublimetext-markdown-preview/issues/347) but they don't help.

I'm using Markdown Preview, and LiveReload. 

Steps to reproduce:

1.  Open .md file in Sublime
2.  Palette -> Markdown Preview: Preview in Browser
3.  Preview opens in browser, looks great
4.  Palette -> LiveReload: Enable/disable plug-ins -> Enable - Simple reload
5.  Status bar message reads: "Simple Reload" the LiveReload plugin as been enabled!
6.  Edit .md file
7.  Save .md file
8.  Status bar message reads: LiveReload refresh from SimpleReloadPlugin
9.  Browser preview does not change
10.  Manually reloading browser page does not change preview, suggesting that Markdown Preview is not writing an updated .html

Running:
* macOS Sierra 10.12.4
* Sublime Text 3 Stable, build 3126
* Markdown Preview 1.4.2
* LiveReload 0.1.3
* Chrome 57.0.2987.133 (but also reproduced the issue in Safari)

Any suggestions?  Been at this for ~2 hours and finally giving up.

Thanks,
James

**Comment by ElfSundae** [comment]
Same here

**Comment by revolunet** [comment]
Hi, sorry for this, you now have to set `enable_autoreload` to true in your settings.
Can you please try and confirm it works ok for you ?

Thanks

**Comment by jhogan4288** [comment]
Hi @revolunet, thanks for the followup!

I tried again to set `enable_autoreload` to `true`, and restarted Sublime.

It still does not work -- *but* I notice that the browser window is actually refreshing.  It was not refreshing before.  However, the content in the browser window still does not update to match the changes to the file.

Additionally, I now see this error in the console, which I was not seeing when `enable_autoreload` was `false`:

```
{"apply_css_live": null, "apply_images_live": null, "apply_js_live": null, "path": "README.MD", "command": "reload"}
INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x10a2373d0>
ERROR:WebSocketClient:WebSocket error
Traceback (most recent call last):
  File "/Users/jhogan/Library/Application Support/Sublime Text 3/Packages/LiveReload/server/WebSocketClient.py", line 84, in __init__
    data = self.socket.recv(1024)
OSError: [Errno 9] Bad file descriptor
INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x10a2373d0>
INFO:WebSocketClient:new client ('127.0.0.1', 62746)
INFO:WebSocketClient:new client ('127.0.0.1', 62748)
INFO:WebSocketClient:Add to clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x10a2a5250>
INFO:WebSocketClient:{'mask': b'\x1f\xf0\x97h', 'close_reason': None, 'opcode': 1, 'payload': b'{"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","snipver":"1"}', 'left': 0, 'hlen': 4, 'fin': 1, 'length': 151, 'close_code': None}
INFO:WebSocketClient:Command: hello
INFO:WebSocketClient:{'mask': b'\x90\xf5\xb9\xb7', 'close_reason': None, 'opcode': 1, 'payload': b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///var/folders/ym/mdc1nynx0l1g7shy16xb77_40000gn/T/30.html"}', 'left': 0, 'hlen': 4, 'fin': 1, 'length': 143, 'close_code': None}
INFO:WebSocketClient:Command: info
b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///var/folders/ym/mdc1nynx0l1g7shy16xb77_40000gn/T/30.html"}'
```

**Comment by ElfSundae** [comment]
For me, after being reinstalled, the Markdown Preview plugin works now.

**Comment by revolunet** [comment]
Can you please try this solution : https://github.com/revolunet/sublimetext-markdown-preview/issues/389#issuecomment-301921456

**Comment by jhogan4288** [comment]
Yeah, #389 is identical to what I did, with the exception that I already had LiveReload installed (so steps 5-6 were steps 1-2).

**Comment by jhogan4288** [comment]
FYI, retried the steps again from #389 for good measure, and the same problem w/the same console error message still persist.

**Comment by facelessuser** [comment]
@jhogan4288, I think I've found the issue with Chrome. Over in #389 I describe my findings here: https://github.com/revolunet/sublimetext-markdown-preview/issues/389#issuecomment-305989535.

It is possible I can make a bug fix release with the livereload `async` patch soon.

**Comment by facelessuser** [comment]
I will close this issue in favor of #389 to cut down on duplicate issues.  Further discussion can be made in issue #389.  I am hoping to have this fixed moving forward.
