### ISSUE TITLE
HTML Preview Refreshing Doesn't Update Document

### ISSUE THREAD

**Issue by tajmone** [revolunet/sublimetext-markdown-preview#389]
I've used this plugin with ST3 (Win 10) for a long time, and when I refreshed the HTML preview in the browser it would update to the newly saved contents.

Since a week or so it doesn't refresh any more: I have to invoke markdown preview (via key bindings) again, in a new html doc. Something has changed with the last ST3 update: it seems that markdown preview is not handling cache very well...

I've seen other issues mention the problem in relation to LiveReload, but I didn't install LiveReload. I've always manually refreshed (Ctrl+F5 or Ctrl+Shift+F5) the HTML preview after saving changes in ST, and it always worked fine.

What can I do? I've tried deleting the cache files of this plugin, but nothing changed. I have the impression it has to do with the ST3 update, that something breaks the plugin. Maybe also the issues with LiveReload are due to the same problem.

Any ideas?

**Comment by DougBeney** [comment]
Same boat.

**Comment by revolunet** [comment]
Hi
Sorry for the convenience !

You now have to set `enable_autoreload` to true in your settings.
Can you please test and confirm it works ok for you ?

**Comment by kingluddite** [comment]
Yes it does work but it took a bit of time. Here are the steps I followed.

1. Sublime Text > Package Settings > Markdown Preview > Settings - User

2. Added

```
{
  "enable_autoreload": true
}
```
3. Saved, shut down Sublime Restarted
4. Then when opened file in browser and refresh the update worked
5. To not have to refresh I installed the LiveReload package for ST
6. Restarted ST
7. Open markdown file in browser
8. Open palette in ST
9. Selected this [screenshot](https://i.imgur.com/rRyJ6mJ.png) (enabled/disable plugins)
10. Chose Enable SimpleReload
11. Then as I made changes and saved them, the page refreshed

Here were two links that helped me figure this out
https://huima.wordpress.com/2014/06/29/sublimetext-markdown-preview-live-reload-epic-markdown-writing-environment/

https://forum.sublimetext.com/t/how-to-use-livereload-in-sublime-text-3/16356/14

Hopefully this saved people the hour it took me. Was it worth it. Of course :)

**Comment by revolunet** [comment]
thanks for reporting the solution 👍

**Comment by tajmone** [comment]
Thanks, it solved the issue and now is working as usual.

**Comment by facelessuser** [comment]
This is actually more complicated then described, but I think I've figured it out.  Even after following these steps, I still had issues.  It would not reload in Chrome.  I found Chrome was intervening due to the way the script behaved; it was blocking it.  I read this article https://developers.google.com/web/updates/2016/08/removing-document-write.

Turns out attaching `async` or `defer` to the script allows it to execute. But then I was always one rev behind.  Ugghh. Well, instead of using `Simple Reload`, I used `Simple Reload with delay (400ms)`.  Now it reloads with the current rev.

In the next release, I will apply `async` to the live reload script to avoid Chrome from intervening.  On top of that, it may be advisable to use `Simple Reload with delay (400ms)`.  I will document this in the readme as well.

**Comment by facelessuser** [comment]
Fix is here: https://github.com/revolunet/sublimetext-markdown-preview/commit/3e866bb442c0be3fa23b230aaa7fcc845bfe2d24

**Comment by facelessuser** [comment]
I released 1.4.3 with the `async` fix and the readme has been updated with instructions on setup.

Hopefully this fixes things for most people and we can finally close this.

**Comment by jhogan4288** [comment]
This worked for me, @facelessuser.  (I was the submitter of #388.)  Thank you!

**Comment by facelessuser** [comment]
Great! I'm glad it worked. I think it was harder to catch as this behavior is different from browser to browser. I unfortunately didn't have the time to look until recently, but luckily it was a simple patch.

**Comment by jhogan4288** [comment]
Makes sense — really appreciate you looking into it.

**Comment by facelessuser** [comment]
Seems like the original posters found a workaround, and it seems I was able to fix the only other issues I could find which seems to help people that the original suggestions didn't fix.  I will consider this closed unless someone reports issues.

**Comment by jhogan4288** [comment]
@facelessuser FWIW, this stopped working for me again.  I'm seeing the following in my console.

At this point, I'll probably throw in the towel and switch to a dedicated Markdown app, but thought you would want to know!

```
 {"path": "README", "apply_images_live": null, "command": "reload", "apply_js_live": null, "apply_css_live": null}
INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x106a58f50>
ERROR:WebSocketClient:WebSocket error
Traceback (most recent call last):
  File "/Users/jhogan/Library/Application Support/Sublime Text 3/Packages/LiveReload/server/WebSocketClient.py", line 84, in __init__
    data = self.socket.recv(1024)
OSError: [Errno 9] Bad file descriptor
INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x106a58f50>
INFO:WebSocketClient:new client ('127.0.0.1', 56734)
INFO:WebSocketClient:new client ('127.0.0.1', 56736)
INFO:WebSocketClient:Add to clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x106a58f50>
INFO:WebSocketClient:{'close_code': None, 'close_reason': None, 'fin': 1, 'payload': b'{"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","snipver":"1"}', 'hlen': 4, 'mask': b'S|\xc6,', 'length': 151, 'left': 0, 'opcode': 1}
INFO:WebSocketClient:Command: hello
INFO:WebSocketClient:{'close_code': None, 'close_reason': None, 'fin': 1, 'payload': b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///var/folders/ym/mdc1nynx0l1g7shy16xb77_40000gn/T/30.html"}', 'hlen': 4, 'mask': b'\x10\xcem\xb6', 'length': 143, 'left': 0, 'opcode': 1}
INFO:WebSocketClient:Command: info
b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///var/folders/ym/mdc1nynx0l1g7shy16xb77_40000gn/T/30.html"}'
```

**Comment by facelessuser** [comment]
Were you using the live reload option with the delay?  I'm not sure how the LiveReload plugin implements the live reload, or how it handles when to stop watching a file as more accumulate, but maybe it's possible for us to directly implement live reload if the plugin is flaky. We've been relying on them.

Anyways, I understand moving to a Markdown app may make sense for you as a working solution now is better than a promised solution in the future.

**Comment by jhogan4288** [comment]
Yes, I tried LiveReload w/the 400ms delay... which worked for me a week or two ago, but not this time.  Weird.

Thanks again for all your efforts.
