### ISSUE TITLE
Can we drop ST2 support?

### ISSUE THREAD

**Issue by facelessuser** [revolunet/sublimetext-markdown-preview#391]
@revolunet, I really want to simplify things moving forward.  Back porting Markdown support to ST2 is a pain. Curious if you are open to dropping it.

**Comment by revolunet** [comment]
Hey ! Totally open to drop it if it costs :) We just need to keep a branch so uses can still get it

**Comment by facelessuser** [comment]
I think it will allow us to move forward and clean up things  a bunch.  What I do with some of my plugins is just keep the branch.  You can also keep the last ST2 tag around for Package Control, but you have to prune your tags on occasions though as Package Control stops searches after around 30 tags.  Whether we keep the Package Control support for ST2 , or just allow  people to manually grab and install the old branch is up to you.  I think with this, we can pick up the current Markdown dependency and stop vendoring our own.  We also won't have to continue vendoring Markdown extensions either.

I think that way it can make it easier to cleanup existing stuff and make maintaining it easier.

When I have time, I'll probably go ahead and create an ST2 branch, and then create a development branch where I can implement it.  There are probably some things I'd like to clean up as well.  We can evaluate then and merge it if it looks good.

**Comment by revolunet** [comment]
sounds good! Will be happy to assist you if you need :)

**Comment by facelessuser** [comment]
Not a problem, I think I have a good idea what I want to do.  Probably just need you to look it over and give your approval once I'm done.  We can decide how to proceed with Package Control once that time comes.

**Comment by jrappen** [comment]
@revolunet @facelessuser

As a reference , Will mentioned ST3 accounting for 97.4% of queries to Package Control in mid October 2017.

**Comment by facelessuser** [comment]
I'm killing all ST2 branches for my plugins in January, but @revolunet will make the decision for this plugin.

**Comment by kerstin** [comment]
It could make sense to create a separate repository for the ST2 code and then set it to read-only.

Might make it easier for people who are not well-versed with GitHub to still get the old plugin while preventing bug reports and feature requests due to the "physical" separation of the two versions. (Obviously there should be cross-linkage between the two repos, with the one for ST2 clearly communicating that development has stopped and that people will need to upgrade to ST3 if they want to benefit from new features etc.)

**Comment by facelessuser** [comment]
@revolunet, it is probably time to make a decision to how we will proceed. Work on the ST3 only 2.0 branch is done.  We already have an `st2` branch.

1. Do we drop ST2 support in package control, and leave the ST2 branch available for manually install and configuration (though there would probably no formal support for it).  This is my vote.

2. Setup Package Control to install st2-0.0.0 releases for ST2 and st3-0.0.0 releases for ST3.  This requires more work to maintain both.

**Comment by revolunet** [comment]
Hey, thanks a lot for the continuous work here !
As i'm not really active anymore on the project and you're the main contributor, we can move the repo somewhere else ?

Can we point package control for ST2 to the ST2 branch directly ?

**Comment by facelessuser** [comment]
Not exactly.  Any new changes they expect to use semantic versioning.  If you are adamant in supporting ST2, you can begin  releasing st3 releases with st3-x.x.x and st2 releases with st2-x.x.x. We can then have package control to install st2-x.x.x releases on ST2 and st3-x.x.x releases on ST3.

My personal experience with this has found that if you aren't regularly releasing ST2 releases or pruning releases between the last ST2 release, Package Control will eventually not be able to to see ST2 releases as it only looks at X number of releases before giving up.  So you have to every once in a while make a new ST2 release, or prune old releases between the ST2 release and the latest ST3 release.  I'm personally dropping ST2 support for all my plugins, but have no problem doing whatever it is you'd like for Markdown Preview.

Just let me know if you want to setup separate ST2 and ST3 releases, or just drop ST2 moving forward.  Either way is fine with me.

**Comment by facelessuser** [comment]
> As i'm not really active anymore on the project and you're the main contributor, we can move the repo somewhere else ?

I didn't notice this the first time I read your message.  If you are looking to move the repo, I'll have to think about it.  I might take it on, but I'll have to think about it.  I maintain too much as is and am not looking to take on more. I don't mind contributing when I have time (it took me 10 months to push this release out), but I'll have to see.

If I took ownership, I'd definitely just drop ST2 which would make this question a moot point.  Worse case scenario, we can move this over to the SublimeText organization.

**Comment by revolunet** [comment]
Hi @facelessuser 

I dont mind for the repo location, its just that **you** deserve the whole credit now :)

And yes we can drop ST2 support to focus on ST3

Thanks !

**Comment by facelessuser** [comment]
@revolunet, so I've been thinking about this, and I think for now we can transfer it over to me.  GitHub should redirect all requests until I update Package Control, so it should be okay. If I decide to transfer it over to the SublimeText organization, I can do that in the future since I am also a member of that organization.

I can make Package Control updates to change ownership and ST2 changes in one shot.

**Comment by facelessuser** [comment]
@revolunet, please let me know if you plan to transfer the repo or not. I'd like to get the recent work out to people. If you wish to not transfer, I could always just operate off a fork, but I need to know how you wish to proceed. I'm okay with forking if we think that will offer a smoother transition.

**Comment by facelessuser** [comment]
I guess to get things rolling, I'll just fork it, and point Package Control at the new fork.

**Comment by facelessuser** [comment]
FYI, new fork is at https://github.com/facelessuser/MarkdownPreview.  Will probably tag a release soon and start the work to redirect Package Control to it.

**Comment by facelessuser** [comment]
Package Control changes are here: https://github.com/wbond/package_control_channel/pull/7068.
New release has been tagged here: https://github.com/facelessuser/MarkdownPreview/releases/tag/st3-2.0.0.

Hopefully the Package Control will merge the changes and the new release will be available soon.

**Comment by facelessuser** [comment]
Yeah, that's a good idea. When package control switchs over, you can safely remove this one, but until then, a note is a good idea.

**Comment by facelessuser** [comment]
Closing this issue as the question has been answered and actions taken to drop ST2 and move to the new repo.
