### ISSUE TITLE
Giving every mention a link in README.md

### ISSUE THREAD

**Issue by aashutoshrathi** [revolunet/sublimetext-markdown-preview#394]
for eg : changing 
`YAML support thanks to @tommi`
to 
YAML support thanks to [@tommi](https://github.com/tommi)

**Comment by aashutoshrathi** [comment]
If we should do it, assign me

**Comment by revolunet** [comment]
Hi! Thanks for reporting

There is an active rewrite in progress by @facelessuser, which focus on ST3. I guess this will be addressed thanks to the more flexible markdown configs (see #393)

**Comment by facelessuser** [comment]
I can take care of it when before the release.

**Comment by facelessuser** [comment]
Taken care of on the dev branch.
