### ISSUE TITLE
meta data not displaying correctly

### ISSUE THREAD

**Issue by rhasson** [revolunet/sublimetext-markdown-preview#396]
Hi, 

I installed markdown-preview and I love it.  I did run into an issue that could be something simple, but as I understand it by default the 'meta' extension is enabled.  When I set the title meta data in my file it displays it rather than populate the HTML title header.

My file is simple:

title: this is a test

##Test

Thanks
Roy

**Comment by facelessuser** [comment]
>  displays it rather than populate the HTML title header

There really isn't enough information here.

Are you using the GitHub parser?  Or the "markdown" (Python Markdown) parser?

I believe that only Python Markdown will handle this, and only when the `meta` extension is enabled.

You can also enable the yaml parsing and use the following with GitHub or Python Markdown.  Just set `strip_yaml_front_matter` to `true` in the settings.

```yml
---
title: this is a test
---
##Test

Thanks
Roy
```

If this doesn't work in the latest release, let me know, but in the next release, which is getting close, I have tested this and it does work.

**Comment by rhasson** [comment]
Yes I was using the Github parser which is why the metadata didn't work.  Thanks for the clarification.  I followed your suggestion and it works.

Thanks,
Roy
