### ISSUE TITLE
Cannot config keyboard shortcut

### ISSUE THREAD

**Issue by yeasy** [revolunet/sublimetext-markdown-preview#399]
Sublime 3

Following the users configurations like: 

{
  "keys": ["ctrl+j"], 
  "command": "markdown_preview", 
  "args": {"target": "browser", "parser":"markdown"},
}

However, when trigger the shortcut keys, there's no response, and from Sublime's console:

```bash
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
```

**Comment by facelessuser** [comment]
I'll have to see if this is reproducible, but I'll let you know what I find when I have a chance.

**Comment by agarbuno** [comment]
Just enclose all your keybindings in square brackets. Like this
```
[{
"keys": ["ctrl+j"],
"command": "markdown_preview",
"args": {"target": "browser", "parser":"markdown"},
}]
```

**Comment by yeasy** [comment]
@agarbuno i tried, but still no working.

And I'm using MacOS.

Could u help share the full config?

Thanks!

**Comment by agarbuno** [comment]
Yes, no problem! Although, it is really equivalent to my earlier response. I am too using Mac OS. 

```
[{ "keys": ["super+shift+m"], "command": "markdown_preview", "args": {"target": "browser", "parser":"markdown"} }]
```

**Comment by yeasy** [comment]
I copied ur configurations to my user settings.
However, it still says "no command for selector: noop:" on my machine with sublime 3.
Thanks!

**Comment by facelessuser** [comment]
Maybe you have another keybinding overriding the one you are trying to define?  Maybe from another package?

**Comment by facelessuser** [comment]
As discussion as stopped on this, I am closing the issue.

**Comment by yeasy** [comment]
@facelessuser no, there's no keybinding with that.
Thanks for the reply!

**Comment by facelessuser** [comment]
Can you post the full content of the keymap file? Also the name and path (relative to Packages) of the keymap file. I want to make sure the filename, file location, and content look good.

**Comment by yeasy** [comment]
sure, do u know where to find them?
i try to find clue from logs, but there's only one-line complain through console.

**Comment by facelessuser** [comment]
How did you add your own config for the key binding?  I just want to know where in your package directory it was.  Was it `Packages/User/Default.sublime-keymap`?  Or a different file?  What was the *full* content?

**Comment by yeasy** [comment]
Oh, it's configured from preference --> package settings --> markdown preview --> settings users.

The entire content is 

```json
{
  "enable_autoreload": true,
  "enable_mathjax": true,
  "enable_highlight": true,
  "enabled_parsers": ["markdown"],
  "keys": ["ctrl+j"],
  "command": "markdown_preview",
  "args": {"target": "browser", "parser":"markdown"},
}]
```

**Comment by facelessuser** [comment]
This explains so much :slightly_smiling_face: .

Go to `Preferences --> Keybindings`  

Put this in that file:

```js
[
    {
        "keys": ["ctrl+j"],
        "command": "markdown_preview",
        "args": {"target": "browser", "parser":"markdown"}
    }
]
````

**Comment by yeasy** [comment]
Thanks, it works!

And why not we add the keybinding support as part of plugins config? I think it was there sometime before, which offers a unique config entry-point with better UE.

Close first, thanks again!

**Comment by facelessuser** [comment]
Because that is the way Sublime works.  Sublime only looks in keymap files for keymaps.

**Comment by lmj0011** [comment]
>Go to Preferences --> Keybindings

Could this be made clear in the docs? https://github.com/revolunet/sublimetext-markdown-preview/issues/399#issuecomment-339752884

**Comment by facelessuser** [comment]
@lmj0011, you could add a section if you like, but it would be best to add to the `dev` branch.  That is the release that is coming soon.  I'm trying to decide if I'm going to personally take the plugin on myself (transfer ownership), or hand it over to the SublimeText org that is home of a number of 3rd party plugins.  Either way, the `dev` branch is planned for the next release.
