### ISSUE TITLE
Commands not listed in the command list

### ISSUE THREAD

**Issue by michaelalhilly** [revolunet/sublimetext-markdown-preview#404]
Hi,

I can't figure out why but the commands for this one package are not available anymore. It was working fine until recently. I reinstalled and still no luck. I'm using Sublime 3 on OS 10.11. Sorry not sure what else I should add.

Any ideas?

**Comment by facelessuser** [comment]
You are going to have to provide some more info, like Sublime version, errors being shown in console (if any).

Also, check that Package Control hasn't disabled your package.  Sometimes that can happen during the package upgrade process.

**Comment by michaelalhilly** [comment]
Uhh. I'm not sure what happened but it's working again. Sorry for wasting your time.
