### ISSUE TITLE
<style>tag is at the head of source code

### ISSUE THREAD

**Issue by djdeo** [revolunet/sublimetext-markdown-preview#405]
The `<style>` tag is very long. when checking the source code of the preview page, the HTML `<body>` tag is at the very end of the page, need to scroll down a while to recognize that we should press the `End` button on the keyboard to reach the bottom.

Can we put the `<body>` tag at the first screen so we don't have to scroll to the end and check the HTML code?

**Comment by facelessuser** [comment]
Style tag should *only* be in the head, so this is not likely to change.

**Comment by djdeo** [comment]
Thanks for your update, may I ask how can i change this locally, which file
shall i edit, thanks again

2017-11-07 4:55 GMT+08:00 Isaac Muse <notifications@github.com>:

**Comment by facelessuser** [comment]
I believe you can specify your own template with this setting: https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L180.

I wouldn't advise putting style anywhere but the head as only JavaScript is designed to work okay like that, but you are free to do as you like.

**Comment by djdeo** [comment]
Thanks, yes, you're right, can we use the <link href="style.css"> at the
head instead? Sorry to have asked so many questions.

2017-11-08 6:50 GMT+08:00 Isaac Muse <notifications@github.com>:

**Comment by facelessuser** [comment]
Live preview and such are only configured to reload the one file. This is just a simple previewer, it is not meant to generate static sites.  I think for now we will continue generating the one file.

Closing as no actionable items.
