### ISSUE TITLE
table show all columns

### ISSUE THREAD

**Issue by weareno1** [revolunet/sublimetext-markdown-preview#406]
![image](https://user-images.githubusercontent.com/18136108/32719093-18a6defc-c89a-11e7-9c7b-5265dd605a90.png)

can't show all 8 columns

**Comment by facelessuser** [comment]
Is the table scrollable?

**Comment by weareno1** [comment]
@facelessuser yes, the table is scrollable

i use table style in cheatsheet
![image](https://user-images.githubusercontent.com/18136108/32839791-85f174ba-ca50-11e7-96cd-f6150336747f.png)

**Comment by facelessuser** [comment]
If your table is too  big, it, it will become scrollable.  That's just the way it is.  If it wasn't scrollable, then we'd have a problem.  You could add override CSS to adjust work wrapping etc. if you are unhappy with how it currently wraps.  But really big tables will eventually overflow, and when that happens, they become scrollable.

**Comment by weareno1** [comment]
@facelessuser thxs
how to override CSS in `ublimetext-markdown-preview` to show all columns?

**Comment by weareno1** [comment]
@facelessuser thxs
how to override CSS in `sublimetext-markdown-preview` to show all columns?

**Comment by weareno1** [comment]
![image](https://user-images.githubusercontent.com/18136108/33167498-afcc6fbe-d078-11e7-84a4-d8c9ab9d847e.png)
![image](https://user-images.githubusercontent.com/18136108/33167518-bd6ef3e4-d078-11e7-9899-35ec50854dce.png)
980px -> 98%
done!
