### ISSUE TITLE
"Back to top" float button

### ISSUE THREAD

**Issue by aditya-a-patil** [revolunet/sublimetext-markdown-preview#408]
For a long file, its tedious to scroll all the way back to top.
Is there a way to add a float button to help go back to the top quickly?

**Comment by facelessuser** [comment]
You can load your own JavaScript via the [`js` setting](https://github.com/revolunet/sublimetext-markdown-preview/blob/master/MarkdownPreview.sublime-settings#L191).

Markdown Preview aims to provide general previewing, but you can add JavaScript to add whatever additional features you'd like.

**Comment by facelessuser** [comment]
No actionable items. Closing issue.
