### ISSUE TITLE
Write .html file to a temp folder (or configurable folder)

### ISSUE THREAD

**Issue by et304383** [revolunet/sublimetext-markdown-preview#409]
If I generate a browser preview of README.md I am getting README.html written to the same directory.

I don't want these files accidentally checked in.  Can we please add configuration for where these temporary files are written?  I've used another similar plugin that wrote to /tmp

**Comment by aeracode** [comment]
Try  `"path_tempfile": "path/to/temp"`  in user settings for Markdown Preview.

**Comment by facelessuser** [comment]
I believe @aeracode answered this question, but if this is still an issue, feel free to open an issue over at https://github.com/facelessuser/MarkdownPreview which will be the new supported repo location moving forward.
