### ISSUE TITLE
Links in README result in 404 error

### ISSUE THREAD

**Issue by kerstin** [revolunet/sublimetext-markdown-preview#414]
Just wanted to report that these two URLs which are linked from the README don't exist:

https://pythonhosted.org/Markdown/extensions/code_hilite.html
https://pythonhosted.org/Markdown/extensions/meta_data.html

**Comment by facelessuser** [comment]
Ahh, yeah, Python Markdown moved their documentation to GitHub pages.

**Comment by vayupranaditya** [comment]
I face 404 error also in LiveReload link on line 215

**Comment by facelessuser** [comment]
Yes, I will try to merge in the fix today or tomorrow.
