### ISSUE TITLE
Installing in ST3 with Package Manager silently fails

### ISSUE THREAD

**Issue by falsephoenix** [revolunet/sublimetext-markdown-preview#417]
I had my computer reimaged recently and downloaded my favored packages as usual. When I try to install your package through these steps:

![image](https://user-images.githubusercontent.com/18650322/36650229-89aa3312-1a5f-11e8-8666-82bfe1b75872.png)

![image](https://user-images.githubusercontent.com/18650322/36650240-9c85200a-1a5f-11e8-8cf8-6a7121ba2eab.png)

![image](https://user-images.githubusercontent.com/18650322/36650366-40554ebc-1a60-11e8-961d-605c7c8f0c11.png)

The taskbar shows the 'installing' message for all of about half a second before disappearing; the package doesn't show up in Preferences > Package Settings and there's no trace of it ever having been installed.

Is there a log somewhere on my computer that I could provide to help figure out what's going on?

**Comment by chouleo0814** [comment]
if you open up console (ctrl + `) in sublime you can see the error. Note that this might be related to a recent update in package control (see their thread #1334)

**Comment by falsephoenix** [comment]
Yep, same thing. [Link](https://github.com/wbond/package_control/issues/1334) for anyone else reading this, as well as the output of Ctrl+` if it helps.

```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'pygments' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```
