### ISSUE TITLE
Cannot install plugin on MacOSX with Sublime 3

### ISSUE THREAD

**Issue by johanhaleby** [revolunet/sublimetext-markdown-preview#418]
I've previously had this plugin installed but I've removed it (using the package manager) and now when I try to install it again I get this in the console when I try to update using the package manager:

```
ignored packages updated to: ["MarkdownLivePreview", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'bs4' is not currently installed; installing...
Package Control: The dependency 'bs4' is not available
Package Control: The dependency 'bs4' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

And I cannot seem to start the plugin the way it's described in the README. I'm using Sublime 3 build 3143.

**Comment by facelessuser** [comment]
bs4 is not required by Markdown Preview, so that is an unrelated issue.

**Comment by johanhaleby** [comment]
Oh ok. The problem still persists though. Is there some other place I can look for more details or should I close the issue regardless?

**Comment by facelessuser** [comment]
I'm unclear what your issue is.  I need some definable issue.  Are commands not showing up in command palette?  Are they showing up, but not working?  Are there errors when you run a command?  Are you trying to run Github parsing or Python Markdown parsing? etc. etc.

In order for me to help, I would need you to narrow your question down to something  I can actually help you with.

**Comment by johanhaleby** [comment]
Unfortunately this is all I get (afaik). Since I cannot install the plugin I can't show you what it looks :/ All I see is what I get in the console above. Quite strange.

**Comment by facelessuser** [comment]
I would look to see if bs4 exists and delete it. Try what is listed here, ignoring the fact that it is for mdpopups, https://github.com/facelessuser/ColorHelper/issues/108#issuecomment-364593214.  Also remove Markdown Preview and reinstall it after all of this.

I don't know what is going on as I don't have enough info debug this, so scorched earth is the best I can offer.  But make sure when once you've cleared up dependency issues, that you install Markdown Preview via Package Control (I assume that is what you were doing from the beginning).

**Comment by tonykor** [comment]
related to #416

**Comment by facelessuser** [comment]
@tonykor, I don't see how these are related. Instead of linking issues, can you provide more information about your issue? I can't help anyone solve their issue if they are unwilling to give details about their issue.

**Comment by facelessuser** [comment]
As I've heard no further information on this, I will assume the issue has been solved.  If not, feel free to reopen with more information.  But please try installation again as recent Package Control issues have hopefully been solved.
