### ISSUE TITLE
Clarify documentation for enable_autoreload

### ISSUE THREAD

**Issue by alexcombessie** [revolunet/sublimetext-markdown-preview#419]
Dumb question, but I could not find it in the documentation. How can I "enable the enable_autoreload setting in MarkdownPreview.sublime-settings" ?

**Comment by morph626** [comment]
If you go to Preferences > Package Settings > Markdown Preview >Settings - User and add `"enable_autoreload": true` between the curly brackets, you should be golden :)

**Comment by facelessuser** [comment]
Thanks for answering this @morph626!

**Comment by alexcombessie** [comment]
Thanks!
