### ISSUE TITLE
mathjax.html tex2jax config: processEscapes

### ISSUE THREAD

**Issue by cameljon** [revolunet/sublimetext-markdown-preview#423]
Requesting processEscapes: false be set to true. For non-math markdowns $ is used too frequently.

This is also recommended by [mathjax](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters) when using $ and $$ as delimiters.

**Comment by facelessuser** [comment]
This will be addressed in some form in the next release which is very close. Most likely the way MathJax is implemented will be changed to a more generalized form. We will most likely setup a generalized JS configuration of MathJax (configured in a more appropriate way), that can easily be overridden with custom options if desired.

**Comment by facelessuser** [comment]
This has been handled on the dev branch. The generalized implementation will set `processEscapes`, but MathJax setup will be a bit different, but documented. Users will be able to override with their own with the new setup.
