### ISSUE TITLE
Allow 2 spaces to indent

### ISSUE THREAD

**Issue by garyking** [revolunet/sublimetext-markdown-preview#424]
Right now, the package requires at least 4 spaces to indent a child list item. Please allow 2 spaces to also indent these as well.

**Comment by facelessuser** [comment]
This is controlled by Python Markdown or GitHub (if you are using the GitHub parser).  The next version will expose the interface to setup and configure your own Python Markdown extensions, so you can work to override existing behavior yourself, but we will not be changing this by default.
