### ISSUE TITLE
How to add `favicon` when export HTML, and add custom style?

### ISSUE THREAD

**Issue by xianghongai** [revolunet/sublimetext-markdown-preview#425]
```
<link rel="icon" type="image/png" href="http://***.com/favicon.png">
<link rel="shortcut icon" type="image/x-icon" href="http://***.com/favicon.ico">
```

```
<style>
.markdown-body code,
.markdown-body samp {
  padding: .15em .1em!important;
  border-radius: .3em !important;
  color: rgb(200, 0, 0) !important;
  background-color: rgba(200, 0, 0, 0.1) !important;
}
</style>
```

**Comment by facelessuser** [comment]
If this is still a problem, please create an issue over at https://github.com/facelessuser/MarkdownPreview as that is the new supported location of this plugin.  Documentation on creating your own custom template for the upcoming 2.0.0 release is here: https://facelessuser.github.io/MarkdownPreview/.  Hopefully Package Control will make the changes and the release will be available soon.
