### ISSUE TITLE
enable_mathjax not working

### ISSUE THREAD

**Issue by jiaxiang-liu** [revolunet/sublimetext-markdown-preview#429]
Hello:

I set "enable_mathjax" to true, but it doesn't render the math equation as expected.

Sublime version: 3.1.1 Build 3176.

Note: I updated sublime this morning, then it doesn't work.

Thanks,

**Comment by facelessuser** [comment]
New repo is here: https://github.com/facelessuser/MarkdownPreview.  If you have issues please create them there.  What you received is a major release with some breaking changes.

Please check out the documentation: https://facelessuser.github.io/MarkdownPreview/extras/.
