### ISSUE TITLE
Jump to currently edited section

### ISSUE THREAD

**Issue by nazikus** [revolunet/sublimetext-markdown-preview#86]
When editing a big wiki document, it would be handy to scroll down browser page (jump) automatically to currently edited section.

For example, if I'm editing wiki document `My doc.md` at section "My Summary ", the preview would navigate browser to corresponding section anchor `my-doc#my-summary`.

**Comment by facelessuser** [comment]
There is currently no plans to implement this feature moving forward.  The project will now be maintained at https://github.com/facelessuser/MarkdownPreview moving forward.
