### ISSUE TITLE
Mathjax

### ISSUE THREAD

**Issue by dpo** [revolunet/sublimetext-markdown-preview#90]
The recent support for Mathjax is an awesome contribution. It is somewhat working for me but I'm having some difficulties. I'm wondering if others are able to reproduce them.

In the following code, the first inline math expression renders well but the second doesn't render at all:

```
# This is a test

Mathjax works well: \\(\int_0^1 f(t) \mathrm{d}t\\).

Mathjax works so-so: \\(\sum_j \gamma_j^2/d_j\\).
```

Same in displaymath:

```
# This is a test

\\[\int_0^1 f(t) \mathrm{d}t\\]

\\[\sum_j \gamma_j^2/d_j\\]

and so forth.
```

Any ideas?

Thanks in advance!

**Comment by wenruofeng** [comment]
I had a related issue. Using underscore in Mathjax expression still results in italic when near braskets:

$$ \mathbf{B} = \mathbf{U}_{ij} \mathbf{\Sigma}_{ij} \mathbf{V}^{\intercal}_{ij} $$  ## doesn't work

$$ \mathbf{B} = \mathbf{U_{ij}} \mathbf{\Sigma_{ij}} \mathbf{V^{\intercal}_{ij}} $$ ## works but not desired

$$ \mathbf{B} = \mathbf{U}\_{ij} \mathbf{\Sigma}\_{ij} \mathbf{V}^{\intercal}\_{ij} $$ ## works with escaping.

**Comment by knight-corvi** [comment]
@wenruofeng You need to use `\_` for use the underscore since Markdown interprets it as  emphasize
